import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { ArrowDown, ArrowUp, ChevronDown, ChevronRight, Edit3, Eye, EyeOff, FolderTree, Plus, Search, Trash2, X } from 'lucide-react';
import { CategoryIcon } from '../CategoryIcon';
import { StaffAccount } from '../../types/adminTypes';
import { CategoryModule, CategoryMutationValues, CategoryRecord, CategoryService } from '../../services/categoryService';

interface Props { staff: StaffAccount; onRefresh?: () => void; }
type Draft = { id?: string; module: CategoryModule; level: number; name: string; slug: string; parent_id: string; icon_key: string; description: string; sort_order: number; status: 'active' | 'inactive' };
const EMPTY: Draft = { module: 'rental', level: 1, name: '', slug: '', parent_id: '', icon_key: 'folder', description: '', sort_order: 0, status: 'active' };
const MODULES: { id: CategoryModule; label: string; color: string }[] = [{ id: 'rental', label: 'Rentals', color: '#1464F4' }, { id: 'job', label: 'Jobs', color: '#08A34F' }, { id: 'service', label: 'Services', color: '#FF650A' }];
const ICONS = ['folder', 'home', 'building', 'car', 'calendar', 'wrench', 'monitor', 'shirt', 'sofa', 'tent', 'heart', 'pawprint', 'briefcase', 'laptop', 'megaphone', 'calculator', 'hotel', 'truck', 'hardhat', 'factory', 'graduationcap', 'shield', 'globe', 'smartphone', 'palette', 'scale', 'camera', 'package'];

export const AdminCategoryView: React.FC<Props> = ({ staff: _staff, onRefresh }) => {
  const [items, setItems] = useState<CategoryRecord[]>([]); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false);
  const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [query, setQuery] = useState('');
  const [module, setModule] = useState<'all' | CategoryModule>('all'); const [showInactive, setShowInactive] = useState(true); const [expanded, setExpanded] = useState<Set<string>>(new Set()); const [draft, setDraft] = useState<Draft | null>(null);

  const load = useCallback(async () => { setLoading(true); setError(''); const result = await CategoryService.getCategories(undefined, { includeInactive: true, forceRefresh: true }); if (result.success) setItems(result.data); else setError(result.error || 'Categories could not be loaded.'); setLoading(false); }, []);
  useEffect(() => { void load(); }, [load]);

  const byId = useMemo(() => new Map(items.map((item) => [item.id, item])), [items]);
  const filtered = useMemo(() => { const q = query.trim().toLowerCase(); const direct = new Set(items.filter((x) => (module === 'all' || x.module === module) && (showInactive || x.status === 'active') && (!q || `${x.name} ${x.slug} ${x.description ?? ''}`.toLowerCase().includes(q))).map((x) => x.id)); if (q) direct.forEach((id) => { let p = byId.get(id)?.parent_id; while (p) { direct.add(p); p = byId.get(p)?.parent_id; } }); return items.filter((x) => direct.has(x.id)); }, [items, module, showInactive, query, byId]);
  const roots = useMemo(() => CategoryService.buildTree(filtered).filter((x) => x.level === 1), [filtered]);
  const counts = useMemo(() => MODULES.map((m) => ({ ...m, levels: [1, 2, 3].map((level) => items.filter((x) => x.module === m.id && x.level === level && x.status === 'active').length) })), [items]);

  const parents = draft ? items.filter((x) => x.module === draft.module && x.level === draft.level - 1) : [];
  const openCreate = (parent?: CategoryRecord, selectedModule?: CategoryModule) => setDraft({ ...EMPTY, module: parent?.module ?? selectedModule ?? (module === 'all' ? 'rental' : module), level: parent ? parent.level + 1 : 1, parent_id: parent?.id ?? '', sort_order: parent?.children?.length ?? 0 });
  const openEdit = (item: CategoryRecord) => setDraft({ id: item.id, module: item.module, level: item.level, name: item.name, slug: item.slug, parent_id: item.parent_id ?? '', icon_key: item.icon_key ?? '', description: item.description ?? '', sort_order: item.sort_order, status: item.status });
  const act = async (operation: () => Promise<void>, message: string) => { setBusy(true); setError(''); setNotice(''); try { await operation(); await load(); setNotice(message); onRefresh?.(); } catch (e) { setError(e instanceof Error ? e.message : 'The category action failed.'); } finally { setBusy(false); } };
  const save = async () => { if (!draft) return; const slug = CategoryService.slugify(draft.slug || draft.name); if (!draft.name.trim() || !slug) { setError('Name and a valid slug are required.'); return; } if (draft.level > 1 && !draft.parent_id) { setError('Choose a parent exactly one level above.'); return; } const values: CategoryMutationValues = { module: draft.module, level: draft.level, name: draft.name.trim(), slug, parent_id: draft.parent_id || null, icon_key: draft.icon_key || null, description: draft.description.trim() || null, sort_order: Number(draft.sort_order), status: draft.status, reason: draft.id ? 'Category details updated' : 'Category created' }; await act(() => draft.id ? CategoryService.updateCategory(draft.id, values) : CategoryService.createCategory(values), draft.id ? 'Category updated.' : 'Category created.'); setDraft(null); };
  const toggle = (item: CategoryRecord) => act(() => CategoryService.setCategoryStatus(item.id, item.status === 'active' ? 'inactive' : 'active'), `Category ${item.status === 'active' ? 'inactivated' : 'activated'}.`);
  const remove = (item: CategoryRecord) => { if (window.confirm(`Delete “${item.name}”? Referenced categories cannot be deleted and should be inactivated instead.`)) void act(() => CategoryService.deleteCategory(item.id), 'Unreferenced category deleted.'); };
  const toggleExpand = (id: string) => setExpanded((current) => { const next = new Set(current); next.has(id) ? next.delete(id) : next.add(id); return next; });

  const row = (item: CategoryRecord): React.ReactNode => { const children = item.children ?? []; const open = expanded.has(item.id) || Boolean(query); return <div key={item.id}>
    <div className={`grid grid-cols-[minmax(0,1fr)_auto] gap-2 border-b border-slate-100 px-3 py-3 ${item.status === 'inactive' ? 'opacity-60' : ''}`} style={{ paddingLeft: `${12 + (item.level - 1) * 22}px` }}>
      <div className="flex min-w-0 items-center gap-2"><button type="button" onClick={() => toggleExpand(item.id)} disabled={!children.length} className="h-7 w-7 shrink-0 rounded-md text-slate-500 disabled:opacity-20" aria-label={open ? 'Collapse category' : 'Expand category'}>{open ? <ChevronDown size={17}/> : <ChevronRight size={17}/>}</button><span className="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-blue-50"><CategoryIcon iconKey={item.icon_key} slug={item.slug} name={item.name} module={item.module} size={18}/></span><div className="min-w-0"><p className="truncate text-sm font-bold text-[#041C43]">{item.name}</p><p className="truncate text-xs text-slate-500">L{item.level} · {item.slug} · order {item.sort_order}</p></div></div>
      <div className="flex items-center gap-1"><span className={`hidden rounded-full px-2 py-1 text-[10px] font-bold sm:inline ${item.status === 'active' ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-500'}`}>{item.status}</span>{item.level < 3 && <button onClick={() => openCreate(item)} className="rounded-lg p-2 text-[#1464F4]" title="Add child"><Plus size={16}/></button>}<button onClick={() => void act(() => CategoryService.reorderCategory(item.id, 'up'), 'Category reordered.')} className="rounded-lg p-2 text-slate-500" title="Move up"><ArrowUp size={15}/></button><button onClick={() => void act(() => CategoryService.reorderCategory(item.id, 'down'), 'Category reordered.')} className="rounded-lg p-2 text-slate-500" title="Move down"><ArrowDown size={15}/></button><button onClick={() => openEdit(item)} className="rounded-lg p-2 text-slate-500" title="Edit"><Edit3 size={16}/></button><button onClick={() => void toggle(item)} className="rounded-lg p-2 text-slate-500" title={item.status === 'active' ? 'Inactivate' : 'Activate'}>{item.status === 'active' ? <EyeOff size={16}/> : <Eye size={16}/>}</button><button onClick={() => remove(item)} className="rounded-lg p-2 text-red-500" title="Delete"><Trash2 size={16}/></button></div>
    </div>{open && children.map(row)}</div>; };

  return <section className="space-y-5 pb-24">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="flex items-center gap-2 text-2xl font-black text-[#041C43]"><FolderTree className="text-[#1464F4]"/>Categories</h1><p className="mt-1 text-sm text-slate-500">The live three-level taxonomy used by Home, search and posting.</p></div><button onClick={() => openCreate()} className="rounded-xl bg-[#1464F4] px-4 py-3 text-sm font-bold text-white"><Plus className="mr-2 inline" size={17}/>Add main category</button></div>
    <div className="grid gap-3 sm:grid-cols-3">{counts.map((m) => <button key={m.id} onClick={() => setModule(module === m.id ? 'all' : m.id)} className={`rounded-2xl border bg-white p-4 text-left ${module === m.id ? 'ring-2 ring-[#1464F4]' : 'border-slate-200'}`}><span className="font-black" style={{ color: m.color }}>{m.label}</span><p className="mt-2 text-xs text-slate-500">L1 {m.levels[0]} · L2 {m.levels[1]} · L3 {m.levels[2]} active</p></button>)}</div>
    <div className="rounded-xl border border-blue-100 bg-blue-50 p-3 text-sm text-[#041C43]">New categories without a specialized posting schema use safe generic fields.</div>
    <div className="flex flex-col gap-3 rounded-2xl border border-slate-200 bg-white p-3 sm:flex-row"><label className="relative flex-1"><Search className="absolute left-3 top-3 text-slate-400" size={18}/><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search name, slug or description" className="w-full rounded-xl border border-slate-200 py-2.5 pl-10 pr-3 text-sm"/></label><label className="flex items-center gap-2 px-2 text-sm font-semibold text-slate-600"><input type="checkbox" checked={showInactive} onChange={(e) => setShowInactive(e.target.checked)}/>Show inactive</label></div>
    {error && <div className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}{notice && <div className="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700">{notice}</div>}
    <div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white"><div className="min-w-[620px]">{loading ? <p className="p-8 text-center text-sm text-slate-500">Loading live categories…</p> : roots.length ? roots.map(row) : <p className="p-8 text-center text-sm text-slate-500">No categories match these filters.</p>}</div></div>
    {draft && <div className="fixed inset-0 z-[100] flex items-end justify-center bg-slate-950/50 p-0 sm:items-center sm:p-4"><div className="max-h-[92vh] w-full overflow-y-auto rounded-t-3xl bg-white p-5 sm:max-w-xl sm:rounded-3xl"><div className="flex items-center justify-between"><h2 className="text-xl font-black text-[#041C43]">{draft.id ? 'Edit category' : `Add level ${draft.level} category`}</h2><button onClick={() => setDraft(null)} className="p-2"><X/></button></div><div className="mt-5 grid gap-4 sm:grid-cols-2">
      <label className="text-sm font-bold">Module<select disabled={Boolean(draft.id || draft.parent_id)} value={draft.module} onChange={(e) => setDraft({ ...draft, module: e.target.value as CategoryModule, parent_id: '' })} className="mt-1 w-full rounded-xl border p-3">{MODULES.map((m) => <option key={m.id} value={m.id}>{m.label}</option>)}</select></label>
      {draft.level > 1 && <label className="text-sm font-bold">Parent<select value={draft.parent_id} onChange={(e) => setDraft({ ...draft, parent_id: e.target.value })} className="mt-1 w-full rounded-xl border p-3"><option value="">Choose parent</option>{parents.map((p) => <option key={p.id} value={p.id}>{p.name}{p.status === 'inactive' ? ' (inactive)' : ''}</option>)}</select></label>}
      <label className="text-sm font-bold">Name<input value={draft.name} onChange={(e) => setDraft({ ...draft, name: e.target.value, slug: draft.id ? draft.slug : CategoryService.slugify(e.target.value) })} className="mt-1 w-full rounded-xl border p-3"/></label><label className="text-sm font-bold">Slug<input value={draft.slug} onChange={(e) => setDraft({ ...draft, slug: CategoryService.slugify(e.target.value) })} className="mt-1 w-full rounded-xl border p-3"/></label>
      <label className="text-sm font-bold">Icon<select value={draft.icon_key} onChange={(e) => setDraft({ ...draft, icon_key: e.target.value })} className="mt-1 w-full rounded-xl border p-3">{ICONS.map((icon) => <option key={icon}>{icon}</option>)}</select></label><div className="flex items-end gap-3 pb-3 text-sm text-slate-500"><span className="grid h-11 w-11 place-items-center rounded-xl bg-blue-50"><CategoryIcon iconKey={draft.icon_key} module={draft.module}/></span>Icon preview</div>
      <label className="text-sm font-bold">Sort order<input type="number" value={draft.sort_order} onChange={(e) => setDraft({ ...draft, sort_order: Number(e.target.value) })} className="mt-1 w-full rounded-xl border p-3"/></label><label className="text-sm font-bold">Status<select value={draft.status} onChange={(e) => setDraft({ ...draft, status: e.target.value as Draft['status'] })} className="mt-1 w-full rounded-xl border p-3"><option value="active">Active</option><option value="inactive">Inactive</option></select></label>
      <label className="text-sm font-bold sm:col-span-2">Description<textarea value={draft.description} onChange={(e) => setDraft({ ...draft, description: e.target.value })} rows={3} className="mt-1 w-full rounded-xl border p-3"/></label></div><div className="mt-6 flex gap-3"><button onClick={() => setDraft(null)} className="flex-1 rounded-xl border p-3 font-bold">Cancel</button><button disabled={busy} onClick={() => void save()} className="flex-1 rounded-xl bg-[#1464F4] p-3 font-bold text-white disabled:opacity-50">{busy ? 'Saving…' : 'Save'}</button></div></div></div>}
  </section>;
};
