import React, { useCallback, useEffect, useState } from 'react';
import { AlertTriangle, CheckCircle2, ChevronDown, Clock, RefreshCw, Search, XCircle } from 'lucide-react';
import { StaffAccount } from '../../types/adminTypes';
import { AdminModerationService, AdminQueueListing, ListingModerationAction } from '../../services/adminModerationService';

interface Props { staff:StaffAccount;onReviewListing:(listingId:string)=>void;onRefresh:()=>void }

export const AdminModerationQueue:React.FC<Props>=({onReviewListing,onRefresh})=>{
  const[rows,setRows]=useState<AdminQueueListing[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[message,setMessage]=useState('');
  const[module,setModule]=useState('all');const[search,setSearch]=useState('');const[reported,setReported]=useState(false);const[from,setFrom]=useState('');const[to,setTo]=useState('');
  const[actionTarget,setActionTarget]=useState<{listing:AdminQueueListing;action:ListingModerationAction}|null>(null);const[reason,setReason]=useState('');const[hasMore,setHasMore]=useState(false);
  const load=useCallback(async(append=false,last?:AdminQueueListing)=>{setLoading(true);setError('');try{const result=await AdminModerationService.getPendingQueue({module:module==='all'?undefined:module,search:search.trim()||undefined,reported:reported?true:undefined,submittedFrom:from?`${from}T00:00:00Z`:undefined,submittedTo:to?`${to}T23:59:59.999Z`:undefined,cursorAt:last?.submittedAt,cursorId:last?.id,limit:25});setRows(current=>append?[...current,...result.rows]:result.rows);setHasMore(result.hasMore)}catch(e){setError(e instanceof Error?e.message:'Queue could not be loaded.')}finally{setLoading(false)}},[module,search,reported,from,to]);
  useEffect(()=>{const timer=setTimeout(()=>{void load(false)},250);return()=>clearTimeout(timer)},[module,search,reported,from,to]);
  const moderate=async()=>{if(!actionTarget)return;if(actionTarget.action!=='approve'&&!reason.trim()){setError('A clear, actionable reason is required.');return}setLoading(true);setError('');try{await AdminModerationService.moderateListing(actionTarget.listing.id,actionTarget.action,reason);setMessage(`${actionTarget.listing.title} was ${actionTarget.action.replace('_',' ')}d.`);setActionTarget(null);setReason('');await load(false);onRefresh()}catch(e){setError(e instanceof Error?e.message:'Moderation failed.')}finally{setLoading(false)}};
  const counts=rows.reduce<Record<string,number>>((a,row)=>{a[row.module]=(a[row.module]||0)+1;return a},{});
  return <div className="space-y-5">
    <div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-black text-slate-900">Global Moderation Queue</h2><p className="text-xs text-slate-500">Live pending listings across every marketplace owner.</p></div><button onClick={()=>void load(false)} className="rounded-xl border border-slate-200 p-2 text-slate-600" aria-label="Refresh queue"><RefreshCw className="h-4 w-4"/></button></div>
      <div className="mt-4 grid gap-3 md:grid-cols-5"><label className="relative md:col-span-2"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Title, UUID, or owner" className="w-full rounded-xl border border-slate-200 py-2.5 pl-9 pr-3 text-xs"/></label><select value={module} onChange={e=>setModule(e.target.value)} className="rounded-xl border border-slate-200 px-3 text-xs"><option value="all">All modules</option><option value="rental">Rentals</option><option value="job">Jobs</option><option value="service">Services</option></select><input type="date" value={from} onChange={e=>setFrom(e.target.value)} className="rounded-xl border border-slate-200 px-3 text-xs" aria-label="Submitted from"/><input type="date" value={to} onChange={e=>setTo(e.target.value)} className="rounded-xl border border-slate-200 px-3 text-xs" aria-label="Submitted to"/></div>
      <label className="mt-3 flex items-center gap-2 text-xs font-semibold text-slate-700"><input type="checkbox" checked={reported} onChange={e=>setReported(e.target.checked)}/> Reported listings only</label>
    </div>
    <div className="grid grid-cols-4 gap-3">{[['Pending',rows.length],['Rentals',counts.rental||0],['Jobs',counts.job||0],['Services',counts.service||0]].map(([label,value])=><div key={String(label)} className="rounded-2xl border border-slate-200 bg-white p-3"><p className="text-[10px] font-bold uppercase text-slate-500">{label}</p><p className="text-2xl font-black text-slate-900">{value}</p></div>)}</div>
    {error&&<p role="alert" className="rounded-xl border border-rose-200 bg-rose-50 p-3 text-xs font-semibold text-rose-700">{error}</p>}{message&&<p className="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-xs font-semibold text-emerald-700">{message}</p>}
    <div className="overflow-hidden rounded-3xl border border-slate-200 bg-white"><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="bg-slate-50 text-[10px] uppercase text-slate-500"><tr><th className="p-4">Listing</th><th className="p-4">Owner</th><th className="p-4">Submitted</th><th className="p-4">Flags</th><th className="p-4 text-right">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map(row=><tr key={row.id}><td className="p-4"><button onClick={()=>onReviewListing(row.id)} className="text-left"><span className="block font-bold text-slate-900">{row.title}</span><span className="text-[10px] text-slate-500">{row.module} · {row.categoryName} · {row.provinceName}</span></button></td><td className="p-4">{row.ownerName}</td><td className="p-4">{new Date(row.submittedAt).toLocaleString()}</td><td className="p-4">{row.reported?<span className="inline-flex items-center gap-1 text-rose-700"><AlertTriangle className="h-3 w-3"/>Reported</span>:'—'}</td><td className="p-4"><div className="flex justify-end gap-2"><button onClick={()=>setActionTarget({listing:row,action:'approve'})} className="rounded-lg bg-emerald-100 p-2 text-emerald-700" title="Approve"><CheckCircle2 className="h-4 w-4"/></button><button onClick={()=>setActionTarget({listing:row,action:'request_changes'})} className="rounded-lg bg-amber-100 p-2 text-amber-700" title="Request changes"><Clock className="h-4 w-4"/></button><button onClick={()=>setActionTarget({listing:row,action:'reject'})} className="rounded-lg bg-rose-100 p-2 text-rose-700" title="Reject"><XCircle className="h-4 w-4"/></button></div></td></tr>)}{!loading&&rows.length===0&&<tr><td colSpan={5} className="p-10 text-center text-slate-500">No pending listings match these filters.</td></tr>}</tbody></table></div>{hasMore&&<button disabled={loading} onClick={()=>void load(true,rows[rows.length-1])} className="flex w-full items-center justify-center gap-2 border-t border-slate-200 p-3 text-xs font-bold text-blue-700">Load more <ChevronDown className="h-4 w-4"/></button>}</div>
    {actionTarget&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/50 p-4"><div className="w-full max-w-md rounded-3xl bg-white p-6"><h3 className="text-lg font-black capitalize">{actionTarget.action.replace('_',' ')}</h3><p className="mt-1 text-xs text-slate-500">{actionTarget.listing.title}</p>{actionTarget.action!=='approve'&&<textarea value={reason} onChange={e=>setReason(e.target.value)} className="mt-4 min-h-28 w-full rounded-xl border border-slate-200 p-3 text-xs" placeholder="Required moderation reason"/>}<div className="mt-4 flex justify-end gap-2"><button onClick={()=>{setActionTarget(null);setReason('')}} className="rounded-xl border px-4 py-2 text-xs font-bold">Cancel</button><button disabled={loading} onClick={()=>void moderate()} className="rounded-xl bg-slate-900 px-4 py-2 text-xs font-bold text-white">Confirm</button></div></div></div>}
  </div>;
};
