-- RENTOURA.LK — MIGRATION 010: SYNC CANONICAL CATEGORY TAXONOMY
-- Synchronizes the entire website category taxonomy from the canonical frontend definitions.
-- Handles Level 1 (Main), Level 2 (Sub), and Level 3 (Third Level / Type) options across rental, job, and service modules.
-- Preserves existing UUIDs where matching, inserts new items, and sets unmatched legacy rows to status = 'inactive'.
-- Repeat-safe & idempotent.

BEGIN;

-- 1. TEMPORARY CANONICAL TAXONOMY STAGING TABLE
CREATE TEMP TABLE temp_canonical_categories (
  module listing_module NOT NULL,
  level integer NOT NULL,
  name text NOT NULL,
  slug text NOT NULL,
  parent_module listing_module,
  parent_slug text,
  parent_level integer,
  sort_order integer NOT NULL DEFAULT 0,
  icon_key text,
  description text
) ON COMMIT DROP;

-- 2. POPULATE STAGING DATA FROM CANONICAL FRONTEND TAXONOMY
INSERT INTO temp_canonical_categories (module, level, name, slug, parent_module, parent_slug, parent_level, sort_order, icon_key, description)
VALUES
  ('rental', 1, 'Property Rentals', 'property-rentals', NULL, NULL, NULL, 0, '🏠', 'Houses, apartments, commercial properties and land for rent'),
  ('rental', 2, 'Houses', 'houses', 'rental', 'property-rentals', 1, 0, '🏡', 'Single family & luxury homes'),
  ('rental', 3, 'Whole House', 'whole-house', 'rental', 'houses', 2, 0, '🏡', 'Entire standalone home'),
  ('rental', 3, 'Luxury House', 'luxury-house', 'rental', 'houses', 2, 1, '✨', 'High-end with amenities'),
  ('rental', 3, 'Furnished House', 'furnished-house', 'rental', 'houses', 2, 2, '🛋️', 'Fully furnished with items'),
  ('rental', 3, 'Unfurnished House', 'unfurnished-house', 'rental', 'houses', 2, 3, '🚪', 'Standard vacant home'),
  ('rental', 2, 'Apartments / Flats', 'apartments-flats', 'rental', 'property-rentals', 1, 1, '🏢', 'Studio to luxury complexes'),
  ('rental', 3, 'Studio Apartment', 'studio-apartment', 'rental', 'apartments-flats', 2, 0, '🚪', 'Compact open layout'),
  ('rental', 3, '1 Bedroom', '1-bedroom', 'rental', 'apartments-flats', 2, 1, '🛏️', 'Single bedroom apartment'),
  ('rental', 3, '2 Bedrooms', '2-bedrooms', 'rental', 'apartments-flats', 2, 2, '🛏️', 'Standard family unit'),
  ('rental', 3, '3 Bedrooms', '3-bedrooms', 'rental', 'apartments-flats', 2, 3, '🛏️', 'Spacious family unit'),
  ('rental', 3, '4+ Bedrooms', '4-bedrooms', 'rental', 'apartments-flats', 2, 4, '🏢', 'Large luxury apartment'),
  ('rental', 3, 'Luxury Apartment', 'luxury-apartment', 'rental', 'apartments-flats', 2, 5, '🌟', 'Pool, gym & security'),
  ('rental', 2, 'Villas', 'villas', 'rental', 'property-rentals', 1, 2, '🏖️', 'Private luxury retreats & holiday homes'),
  ('rental', 2, 'Bungalows', 'bungalows', 'rental', 'property-rentals', 1, 3, '🏛️', 'Colonial & modern estate bungalows'),
  ('rental', 2, 'Annex / Portions', 'annex-portions', 'rental', 'property-rentals', 1, 4, '🚪', 'Separate portion of house with kitchen'),
  ('rental', 2, 'Holiday Homes', 'holiday-homes', 'rental', 'property-rentals', 1, 5, '🌴', 'Vacation stays & weekend villas'),
  ('rental', 2, 'Commercial Properties', 'commercial-properties', 'rental', 'property-rentals', 1, 6, '🏬', 'Offices, shops, showrooms & retail'),
  ('rental', 3, 'Office', 'office', 'rental', 'commercial-properties', 2, 0, '💼', 'Corporate office space'),
  ('rental', 3, 'Shop / Retail', 'shop-retail', 'rental', 'commercial-properties', 2, 1, '🛍️', 'Retail storefront & kiosk'),
  ('rental', 3, 'Warehouse', 'warehouse', 'rental', 'commercial-properties', 2, 2, '🏭', 'Storage & logistics facility'),
  ('rental', 3, 'Restaurant Space', 'restaurant-space', 'rental', 'commercial-properties', 2, 3, '🍽️', 'Food & beverage setup'),
  ('rental', 3, 'Commercial Building', 'commercial-building', 'rental', 'commercial-properties', 2, 4, '🏢', 'Entire multi-story building'),
  ('rental', 3, 'Industrial Building', 'industrial-building', 'rental', 'commercial-properties', 2, 5, '⚙️', 'Factory & workshop'),
  ('rental', 2, 'Office Spaces', 'office-spaces', 'rental', 'property-rentals', 1, 7, '💼', 'Private offices & co-working spaces'),
  ('rental', 2, 'Shops / Retail Spaces', 'shops-retail', 'rental', 'property-rentals', 1, 8, '🛍️', 'Storefronts, showrooms & kiosks'),
  ('rental', 2, 'Warehouses', 'warehouses', 'rental', 'property-rentals', 1, 9, '📦', 'Commercial storage & distribution yards'),
  ('rental', 2, 'Restaurants / Food Spaces', 'restaurants-food-spaces', 'rental', 'property-rentals', 1, 10, '🍽️', 'Cafes, bakeries & food stalls'),
  ('rental', 2, 'Hotels / Guest Houses', 'hotels-guesthouses', 'rental', 'property-rentals', 1, 11, '🏨', 'Tourism property & boutique hotels'),
  ('rental', 2, 'Industrial Buildings', 'industrial-buildings', 'rental', 'property-rentals', 1, 12, '🏭', 'Factories, production & storage plants'),
  ('rental', 2, 'Land', 'land', 'rental', 'property-rentals', 1, 13, '🏞️', 'Plots, bare land & estates'),
  ('rental', 3, 'Residential Land', 'residential-land', 'rental', 'land', 2, 0, '🏡', 'For housing & apartments'),
  ('rental', 3, 'Commercial Land', 'commercial-land', 'rental', 'land', 2, 1, '🏬', 'Main road commercial plot'),
  ('rental', 3, 'Agricultural Land', 'agricultural-land', 'rental', 'land', 2, 2, '🌾', 'Cultivation & paddy field'),
  ('rental', 3, 'Industrial Land', 'industrial-land', 'rental', 'land', 2, 3, '🏭', 'For factories & heavy storage'),
  ('rental', 1, 'Rooms & Accommodation', 'rooms-accommodation', NULL, NULL, NULL, 1, '🛏️', 'Rooms, boarding, student hostels & shared stays'),
  ('rental', 2, 'Single Room', 'single-room', 'rental', 'rooms-accommodation', 1, 0, '🛏️', 'Private room for 1 person'),
  ('rental', 3, 'Attached Bathroom', 'attached-bathroom', 'rental', 'single-room', 2, 0, '🚿', 'Private en-suite washroom'),
  ('rental', 3, 'Shared Bathroom', 'shared-bathroom', 'rental', 'single-room', 2, 1, '🚪', 'Common bathroom access'),
  ('rental', 3, 'Furnished', 'furnished', 'rental', 'single-room', 2, 2, '🛋️', 'Bed, table & fan/AC provided'),
  ('rental', 3, 'Unfurnished', 'unfurnished', 'rental', 'single-room', 2, 3, '🪑', 'Room only'),
  ('rental', 2, 'Double Room', 'double-room', 'rental', 'rooms-accommodation', 1, 1, '👥', 'Room for 2 persons / couple'),
  ('rental', 2, 'Shared Room', 'shared-room', 'rental', 'rooms-accommodation', 1, 2, '🤝', 'Shared bed space / roommate'),
  ('rental', 2, 'Boarding Room', 'boarding-room', 'rental', 'rooms-accommodation', 1, 3, '🏠', 'Monthly boarding place (Bodim)'),
  ('rental', 2, 'Hostel', 'hostel', 'rental', 'rooms-accommodation', 1, 4, '🏢', 'Student & working hostels'),
  ('rental', 2, 'Student Accommodation', 'student-accommodation', 'rental', 'rooms-accommodation', 1, 5, '🎓', 'Near universities & institutes'),
  ('rental', 2, 'Staff Accommodation', 'staff-accommodation', 'rental', 'rooms-accommodation', 1, 6, '👔', 'Company / employee quarters'),
  ('rental', 2, 'Short Stay Room', 'short-stay-room', 'rental', 'rooms-accommodation', 1, 7, '⏰', 'Daily & weekly rental rooms'),
  ('rental', 2, 'Guest Room', 'guest-room', 'rental', 'rooms-accommodation', 1, 8, '🛎️', 'Homestay & tourist rooms'),
  ('rental', 1, 'Vehicles', 'vehicles', NULL, NULL, NULL, 2, '🚗', 'Cars, vans, buses, three-wheelers, bikes, trucks & boats'),
  ('rental', 2, 'Cars', 'cars', 'rental', 'vehicles', 1, 0, '🚗', 'Sedans, SUVs, hatchbacks & luxury cars'),
  ('rental', 3, 'Economy Car', 'economy-car', 'rental', 'cars', 2, 0, '🚙', 'Wagon R, Alto, Vitz'),
  ('rental', 3, 'Sedan', 'sedan', 'rental', 'cars', 2, 1, '🚗', 'Axio, Premio, Civic, Yaris'),
  ('rental', 3, 'Hatchback', 'hatchback', 'rental', 'cars', 2, 2, '🚗', 'Compact city car'),
  ('rental', 3, 'SUV', 'suv', 'rental', 'cars', 2, 3, '🚙', 'Prado, Vezel, CR-V, Montero'),
  ('rental', 3, 'Luxury Car', 'luxury-car', 'rental', 'cars', 2, 4, '✨', 'Mercedes, BMW, Audi'),
  ('rental', 3, 'Electric Car', 'electric-car', 'rental', 'cars', 2, 5, '⚡', 'EVs & Tesla'),
  ('rental', 3, 'Hybrid Car', 'hybrid-car', 'rental', 'cars', 2, 6, '🔋', 'Fuel-efficient hybrid vehicles'),
  ('rental', 3, 'Sports Car', 'sports-car', 'rental', 'cars', 2, 7, '🏎️', 'Convertible & coupe'),
  ('rental', 2, 'Vans', 'vans', 'rental', 'vehicles', 1, 1, '🚐', 'Passenger, KDH & cargo vans'),
  ('rental', 3, 'Passenger Van', 'passenger-van', 'rental', 'vans', 2, 0, '🚐', 'KDH, HiAce 9-14 seats'),
  ('rental', 3, 'Cargo Van', 'cargo-van', 'rental', 'vans', 2, 1, '📦', 'Delivery & goods transport'),
  ('rental', 3, 'Luxury Van', 'luxury-van', 'rental', 'vans', 2, 2, '✨', 'Super GL, VIP interior'),
  ('rental', 2, 'Buses', 'buses', 'rental', 'vehicles', 1, 2, '🚌', 'Mini buses, coaches & staff transport'),
  ('rental', 3, 'Mini Bus', 'mini-bus', 'rental', 'buses', 2, 0, '🚐', 'Rosa, Coaster 20-30 seats'),
  ('rental', 3, 'Staff Transport Bus', 'staff-transport-bus', 'rental', 'buses', 2, 1, '🚌', 'Office & factory route'),
  ('rental', 3, 'Coach Bus', 'coach-bus', 'rental', 'buses', 2, 2, '🚎', 'Luxury AC 40-54 seats'),
  ('rental', 3, 'Tourist Bus', 'tourist-bus', 'rental', 'buses', 2, 3, '🌴', 'Tours & excursions'),
  ('rental', 2, 'Three Wheelers', 'three-wheelers', 'rental', 'vehicles', 1, 3, '🛺', 'Bajaj, TVS, Piaggio tuk-tuks'),
  ('rental', 2, 'Motorcycles', 'motorcycles', 'rental', 'vehicles', 1, 4, '🏍️', 'Scooters, street bikes & trail bikes'),
  ('rental', 3, 'Scooter', 'scooter', 'rental', 'motorcycles', 2, 0, '🛵', 'Dio, Pleasure, Activa, N-Torq'),
  ('rental', 3, 'Motorbike', 'motorbike', 'rental', 'motorcycles', 2, 1, '🏍️', 'Pulsar, FZ, Discovery, CB'),
  ('rental', 3, 'Sports Bike', 'sports-bike', 'rental', 'motorcycles', 2, 2, '🏍️', 'CBR, R15, KTM Duke'),
  ('rental', 3, 'Touring Bike', 'touring-bike', 'rental', 'motorcycles', 2, 3, '🛣️', 'Adventure & cruiser'),
  ('rental', 2, 'Bicycles', 'bicycles', 'rental', 'vehicles', 1, 5, '🚲', 'City, mountain & electric bicycles'),
  ('rental', 3, 'City Bicycle', 'city-bicycle', 'rental', 'bicycles', 2, 0, '🚲', 'Standard commute bike'),
  ('rental', 3, 'Mountain Bicycle', 'mountain-bicycle', 'rental', 'bicycles', 2, 1, '🚵', 'MTB with gears & suspension'),
  ('rental', 3, 'Road Bicycle', 'road-bicycle', 'rental', 'bicycles', 2, 2, '🚴', 'Speed racing bike'),
  ('rental', 3, 'Electric Bicycle', 'electric-bicycle', 'rental', 'bicycles', 2, 3, '⚡', 'E-bike pedal assist'),
  ('rental', 2, 'Trucks & Lorries', 'trucks-lorries', 'rental', 'vehicles', 1, 6, '🚛', 'Pickups, mini-lorries, tippers & containers'),
  ('rental', 3, 'Pickup', 'pickup', 'rental', 'trucks-lorries', 2, 0, '🛻', 'Hilux, D-Max, Cab'),
  ('rental', 3, 'Mini Lorry', 'mini-lorry', 'rental', 'trucks-lorries', 2, 1, '🚚', 'Dimo Batta, Tata Ace, Mahindra'),
  ('rental', 3, 'Lorry', 'lorry', 'rental', 'trucks-lorries', 2, 2, '🚛', 'Canter, Isuzu Elf, 10-14ft'),
  ('rental', 3, 'Heavy Truck', 'heavy-truck', 'rental', 'trucks-lorries', 2, 3, '🚚', 'Multi-axle & heavy payload'),
  ('rental', 3, 'Container Truck', 'container-truck', 'rental', 'trucks-lorries', 2, 4, '📦', '20ft / 40ft prime mover'),
  ('rental', 2, 'Construction Vehicles', 'construction-vehicles', 'rental', 'vehicles', 1, 7, '🚜', 'Excavators, backhoes, cranes & tractors'),
  ('rental', 3, 'Excavator', 'excavator', 'rental', 'construction-vehicles', 2, 0, '🚜', 'Track & wheeled digger (Kobelco/CAT)'),
  ('rental', 3, 'Backhoe (JCB)', 'backhoe-jcb', 'rental', 'construction-vehicles', 2, 1, '🚜', 'JCB / loader combo'),
  ('rental', 3, 'Bulldozer', 'bulldozer', 'rental', 'construction-vehicles', 2, 2, '🚜', 'Earthmoving & grading'),
  ('rental', 3, 'Crane', 'crane', 'rental', 'construction-vehicles', 2, 3, '🏗️', 'Mobile hydraulic & boom truck'),
  ('rental', 3, 'Road Roller', 'road-roller', 'rental', 'construction-vehicles', 2, 4, '🚜', 'Soil & asphalt compactor'),
  ('rental', 3, 'Tractor', 'tractor', 'rental', 'construction-vehicles', 2, 5, '🚜', 'Farm & trailer tractor'),
  ('rental', 3, 'Loader', 'loader', 'rental', 'construction-vehicles', 2, 6, '🚜', 'Wheel loader for sand & gravel'),
  ('rental', 3, 'Dump Truck', 'dump-truck', 'rental', 'construction-vehicles', 2, 7, '🚛', 'Tipper for earth & gravel'),
  ('rental', 2, 'Water Transport', 'water-transport', 'rental', 'vehicles', 1, 8, '🚤', 'Speed boats, fishing boats, yachts & jet skis'),
  ('rental', 3, 'Boat', 'boat', 'rental', 'water-transport', 2, 0, '⛵', 'Motorized boat for lagoon & river'),
  ('rental', 3, 'Fishing Boat', 'fishing-boat', 'rental', 'water-transport', 2, 1, '🎣', 'Deep sea & coastal fishing'),
  ('rental', 3, 'Speed Boat', 'speed-boat', 'rental', 'water-transport', 2, 2, '🚤', 'Water sports & fast charter'),
  ('rental', 3, 'Yacht', 'yacht', 'rental', 'water-transport', 2, 3, '🛥️', 'Luxury sailing & party yacht'),
  ('rental', 3, 'Jet Ski', 'jet-ski', 'rental', 'water-transport', 2, 4, '🌊', 'Personal watercraft'),
  ('rental', 1, 'Event Rentals', 'event-rentals', NULL, NULL, NULL, 3, '🎉', 'Halls, canopies, lights, sound systems, catering & DJ items'),
  ('rental', 2, 'Wedding Hall', 'wedding-hall', 'rental', 'event-rentals', 1, 0, '💒', 'Banquet halls & ballroom venues'),
  ('rental', 2, 'Reception Hall', 'reception-hall', 'rental', 'event-rentals', 1, 1, '🏛️', 'Ceremony & dinner venues'),
  ('rental', 2, 'Party Hall', 'party-hall', 'rental', 'event-rentals', 1, 2, '🎈', 'Birthdays & get-togethers'),
  ('rental', 2, 'Conference Hall', 'conference-hall', 'rental', 'event-rentals', 1, 3, '🏢', 'Auditoriums & seminars'),
  ('rental', 2, 'Meeting Room', 'meeting-room', 'rental', 'event-rentals', 1, 4, '💼', 'Boardroom & training rooms'),
  ('rental', 2, 'Event Ground', 'event-ground', 'rental', 'event-rentals', 1, 5, '🎪', 'Open-air grounds & turf fields'),
  ('rental', 2, 'Stage & Trussing', 'stage-trussing', 'rental', 'event-rentals', 1, 6, '🎭', 'Modular platforms & backdrop framing'),
  ('rental', 2, 'Sound System', 'sound-system', 'rental', 'event-rentals', 1, 7, '🔊', 'Speakers, line-arrays & microphones'),
  ('rental', 2, 'DJ Equipment', 'dj-equipment', 'rental', 'event-rentals', 1, 8, '🎧', 'DJ consoles, mixers & decks'),
  ('rental', 2, 'Lighting Equipment', 'lighting-equipment', 'rental', 'event-rentals', 1, 9, '💡', 'Moving heads, par lights & lasers'),
  ('rental', 2, 'LED Screen & Walls', 'led-screen-walls', 'rental', 'event-rentals', 1, 10, '🖥️', 'Indoor & outdoor video walls'),
  ('rental', 2, 'Projector & Screens', 'projector-screens', 'rental', 'event-rentals', 1, 11, '📽️', 'HD projectors & pull-up screens'),
  ('rental', 2, 'Tents & Marquees', 'tents-marquees', 'rental', 'event-rentals', 1, 12, '⛺', 'Canopies, huts & wedding tents'),
  ('rental', 2, 'Chairs & Tables', 'chairs-tables', 'rental', 'event-rentals', 1, 13, '🪑', 'Plastic, banquet & chiavari chairs'),
  ('rental', 2, 'Decorations & Backdrops', 'decorations-backdrops', 'rental', 'event-rentals', 1, 14, '💐', 'Floral, thematic & balloon arches'),
  ('rental', 2, 'Generator', 'generator', 'rental', 'event-rentals', 1, 15, '⚡', 'Event backup power generators'),
  ('rental', 2, 'Portable AC & Fans', 'portable-ac-fans', 'rental', 'event-rentals', 1, 16, '❄️', 'Mist fans & temporary marquee cooling'),
  ('rental', 2, 'Photo Booth', 'photo-booth', 'rental', 'event-rentals', 1, 17, '📸', '360 video booth & props'),
  ('rental', 2, 'Wedding Car', 'wedding-car', 'rental', 'event-rentals', 1, 18, '🚘', 'Decorated luxury & vintage cars'),
  ('rental', 1, 'Construction & Industrial Equipment', 'construction-industrial-equipment', NULL, NULL, NULL, 4, '🏗️', 'Scaffolding, mixers, generators, pumps, compactors & heavy tools'),
  ('rental', 2, 'Scaffolding', 'scaffolding', 'rental', 'construction-industrial-equipment', 1, 0, '🪜', 'Steel frames, pipes & jacks'),
  ('rental', 2, 'Generators', 'generators', 'rental', 'construction-industrial-equipment', 1, 1, '⚡', 'Diesel & petrol standby power (5kVA - 500kVA)'),
  ('rental', 2, 'Water Pumps', 'water-pumps', 'rental', 'construction-industrial-equipment', 1, 2, '💧', 'Submersible, dewatering & petrol pumps'),
  ('rental', 2, 'Air Compressors', 'air-compressors', 'rental', 'construction-industrial-equipment', 1, 3, '💨', 'Pneumatic compressors & hoses'),
  ('rental', 2, 'Welding Machines', 'welding-machines', 'rental', 'construction-industrial-equipment', 1, 4, '🔥', 'Arc, TIG & MIG welders'),
  ('rental', 2, 'Concrete Mixers', 'concrete-mixers', 'rental', 'construction-industrial-equipment', 1, 5, '⚙️', 'Batching mixers & poker vibrators'),
  ('rental', 2, 'Compactors & Rammers', 'compactors-rammers', 'rental', 'construction-industrial-equipment', 1, 6, '🔨', 'Plate compactors & roller rammers'),
  ('rental', 2, 'Survey Equipment', 'survey-equipment', 'rental', 'construction-industrial-equipment', 1, 7, '📐', 'Total stations, theodolites & dumpy levels'),
  ('rental', 1, 'Tools & Machinery', 'tools-machinery', NULL, NULL, NULL, 5, '🔧', 'Drills, grinders, cutters, pressure washers & power hand tools'),
  ('rental', 2, 'Power Tools', 'power-tools', 'rental', 'tools-machinery', 1, 0, '🪛', 'Drills, angle grinders & impact wrenches'),
  ('rental', 2, 'Hand Tools', 'hand-tools', 'rental', 'tools-machinery', 1, 1, '🔨', 'Wrenches, spanners, pliers & kits'),
  ('rental', 2, 'Tile Cutters', 'tile-cutters', 'rental', 'tools-machinery', 1, 2, '🪚', 'Electric & manual ceramic/granite cutters'),
  ('rental', 2, 'Drilling Machines', 'drilling-machines', 'rental', 'tools-machinery', 1, 3, '🔩', 'Rotary hammers, core drills & magnetic drills'),
  ('rental', 2, 'Cutting Machines', 'cutting-machines', 'rental', 'tools-machinery', 1, 4, '🪚', 'Chop saws, circular saws & metal cutters'),
  ('rental', 2, 'Ladders', 'ladders', 'rental', 'tools-machinery', 1, 5, '🪜', 'Aluminum extension & A-frame ladders'),
  ('rental', 2, 'Pressure Washers', 'pressure-washers', 'rental', 'tools-machinery', 1, 6, '💦', 'High pressure water jet cleaners'),
  ('rental', 1, 'Electronics & Technology', 'electronics-technology', NULL, NULL, NULL, 6, '💻', 'Laptops, computers, TVs, tablets, gaming consoles & tech devices'),
  ('rental', 2, 'Laptop', 'laptop', 'rental', 'electronics-technology', 1, 0, '💻', 'Business, student & gaming laptops'),
  ('rental', 2, 'Desktop Computer', 'desktop-computer', 'rental', 'electronics-technology', 1, 1, '🖥️', 'High performance PC towers & all-in-ones'),
  ('rental', 2, 'Monitor / Display', 'monitor-display', 'rental', 'electronics-technology', 1, 2, '🖥️', '24" to 34" LED/IPS monitors'),
  ('rental', 2, 'Printer / Scanner', 'printer-scanner', 'rental', 'electronics-technology', 1, 3, '🖨️', 'Laser, inkjet & multifunction photocopiers'),
  ('rental', 2, 'Projector', 'projector', 'rental', 'electronics-technology', 1, 4, '📽️', 'Home theater & presentation projectors'),
  ('rental', 2, 'TV', 'tv', 'rental', 'electronics-technology', 1, 5, '📺', '43" - 75" Smart 4K displays'),
  ('rental', 2, 'Tablet / iPad', 'tablet-ipad', 'rental', 'electronics-technology', 1, 6, '📱', 'iPads & Android tablets for events'),
  ('rental', 2, 'Gaming Console', 'gaming-console', 'rental', 'electronics-technology', 1, 7, '🎮', 'PlayStation 5, PS4, Xbox, Nintendo Switch'),
  ('rental', 2, 'VR Headset', 'vr-headset', 'rental', 'electronics-technology', 1, 8, '🥽', 'Meta Quest & VR gaming gear'),
  ('rental', 2, 'Router & Networking', 'router-networking', 'rental', 'electronics-technology', 1, 9, '📡', '4G/5G routers, switches & WiFi access points'),
  ('rental', 2, 'UPS & Power Bank', 'ups-power-bank', 'rental', 'electronics-technology', 1, 10, '🔋', 'High-capacity battery stations'),
  ('rental', 1, 'Cameras & Media Equipment', 'cameras-media-equipment', NULL, NULL, NULL, 7, '📷', 'DSLR, mirrorless, lenses, drones, gimbals & studio lighting gear'),
  ('rental', 2, 'DSLR Camera', 'dslr-camera', 'rental', 'cameras-media-equipment', 1, 0, '📷', 'Canon & Nikon DSLR bodies'),
  ('rental', 2, 'Mirrorless Camera', 'mirrorless-camera', 'rental', 'cameras-media-equipment', 1, 1, '📸', 'Sony Alpha, Canon R, Fujifilm bodies'),
  ('rental', 2, 'Video Camera', 'video-camera', 'rental', 'cameras-media-equipment', 1, 2, '🎥', 'Cinema cameras (FX3, BMPCC, RED)'),
  ('rental', 2, 'Action Camera', 'action-camera', 'rental', 'cameras-media-equipment', 1, 3, '📹', 'GoPro Hero & Insta360 cameras'),
  ('rental', 2, 'Lenses', 'lenses', 'rental', 'cameras-media-equipment', 1, 4, '🔍', 'Prime, zoom, telephoto & wide-angle lenses'),
  ('rental', 2, 'Drone', 'drone', 'rental', 'cameras-media-equipment', 1, 5, '🛸', 'DJI Mavic, Mini & Phantom series'),
  ('rental', 2, 'Gimbal & Stabilizer', 'gimbal-stabilizer', 'rental', 'cameras-media-equipment', 1, 6, '🕹️', 'DJI Ronin, RS3, Zhiyun gimbals'),
  ('rental', 2, 'Tripod & Monopod', 'tripod-monopod', 'rental', 'cameras-media-equipment', 1, 7, '🔭', 'Heavy duty video & photo tripods'),
  ('rental', 2, 'Studio Lighting Kit', 'studio-lighting-kit', 'rental', 'cameras-media-equipment', 1, 8, '💡', 'Godox, Aputure softboxes & LED lights'),
  ('rental', 2, 'Microphone & Audio', 'microphone-audio', 'rental', 'cameras-media-equipment', 1, 9, '🎙️', 'Rode wireless mics, Zoom recorders'),
  ('rental', 1, 'Furniture', 'furniture', NULL, NULL, NULL, 8, '🛋️', 'Sofas, beds, dining sets, office desks & event furniture'),
  ('rental', 2, 'Sofa & Couches', 'sofa-couches', 'rental', 'furniture', 1, 0, '🛋️', 'Living room sofas, recliners & L-shapes'),
  ('rental', 2, 'Bed & Mattress', 'bed-mattress', 'rental', 'furniture', 1, 1, '🛏️', 'King, queen & single beds with mattresses'),
  ('rental', 2, 'Dining Table & Chairs', 'dining-table-chairs', 'rental', 'furniture', 1, 2, '🪑', '4-8 seater wooden & glass sets'),
  ('rental', 2, 'Wardrobe & Closets', 'wardrobe-closets', 'rental', 'furniture', 1, 3, '🚪', '2-4 door almirahs & cloth racks'),
  ('rental', 2, 'Office Desk & Workstation', 'office-desk-workstation', 'rental', 'furniture', 1, 4, '💼', 'Executive desks & computer tables'),
  ('rental', 2, 'Office Chair', 'office-chair', 'rental', 'furniture', 1, 5, '🪑', 'Ergonomic mesh & leather chairs'),
  ('rental', 2, 'Conference Table', 'conference-table', 'rental', 'furniture', 1, 6, '🏢', 'Boardroom meeting tables'),
  ('rental', 2, 'Outdoor Furniture', 'outdoor-furniture', 'rental', 'furniture', 1, 7, '🪑', 'Patio chairs, garden tables & benches'),
  ('rental', 2, 'Storage Cabinet & Racks', 'storage-cabinet-racks', 'rental', 'furniture', 1, 8, '🗄️', 'Bookcases, filing cabinets & display racks'),
  ('rental', 1, 'Home Appliances', 'home-appliances', NULL, NULL, NULL, 9, '🧊', 'Fridges, washing machines, microwaves, ACs & household appliances'),
  ('rental', 2, 'Refrigerator & Freezer', 'refrigerator-freezer', 'rental', 'home-appliances', 1, 0, '🧊', 'Single & double door fridges, deep freezers'),
  ('rental', 2, 'Washing Machine', 'washing-machine', 'rental', 'home-appliances', 1, 1, '🧺', 'Top load & front load automatic washers'),
  ('rental', 2, 'Air Conditioner', 'air-conditioner', 'rental', 'home-appliances', 1, 2, '❄️', 'Split & portable AC units'),
  ('rental', 2, 'Microwave & Oven', 'microwave-oven', 'rental', 'home-appliances', 1, 3, '🍲', 'Convection microwaves & baking ovens'),
  ('rental', 2, 'Cooker / Stove', 'cooker-stove', 'rental', 'home-appliances', 1, 4, '🍳', 'Gas burners, induction & rice cookers'),
  ('rental', 2, 'Fans', 'fans', 'rental', 'home-appliances', 1, 5, '💨', 'Stand fans, ceiling fans & tower fans'),
  ('rental', 2, 'Water Dispenser', 'water-dispenser', 'rental', 'home-appliances', 1, 6, '💧', 'Hot & cold bottle dispensers'),
  ('rental', 2, 'Vacuum Cleaner', 'vacuum-cleaner', 'rental', 'home-appliances', 1, 7, '🧹', 'Wet/dry vacuums & carpet cleaners'),
  ('rental', 2, 'Water Heater', 'water-heater', 'rental', 'home-appliances', 1, 8, '🚿', 'Geysers & instant water heaters'),
  ('rental', 1, 'Fashion & Clothing', 'fashion-clothing', NULL, NULL, NULL, 10, '👗', 'Suits, blazers, sarees, party wear & designer apparel'),
  ('rental', 2, 'Suit & Tuxedo', 'suit-tuxedo', 'rental', 'fashion-clothing', 1, 0, '👔', 'Men’s formal suits, blazers & tuxedos'),
  ('rental', 2, 'Blazer', 'blazer', 'rental', 'fashion-clothing', 1, 1, '🧥', 'Casual & business blazers'),
  ('rental', 2, 'Saree', 'saree', 'rental', 'fashion-clothing', 1, 2, '🥻', 'Silk, designer & party wear sarees'),
  ('rental', 2, 'Evening Dress & Gown', 'evening-dress-gown', 'rental', 'fashion-clothing', 1, 3, '👗', 'Party wear gowns & cocktail dresses'),
  ('rental', 2, 'Kurta & Sherwani', 'kurta-sherwani', 'rental', 'fashion-clothing', 1, 4, '🥻', 'Traditional ethnic wear'),
  ('rental', 2, 'Costumes & Fancy Dress', 'costumes-fancy-dress', 'rental', 'fashion-clothing', 1, 5, '🎭', 'Character, cultural & Halloween wear'),
  ('rental', 1, 'Wedding & Bridal Items', 'wedding-bridal-items', NULL, NULL, NULL, 11, '💍', 'Bridal sarees, gowns, jewellery, nilame suits & bridal accessories'),
  ('rental', 2, 'Bridal Saree', 'bridal-saree', 'rental', 'wedding-bridal-items', 1, 0, '🥻', 'Kandyan & Indian bridal sarees'),
  ('rental', 2, 'Bridal Gown', 'bridal-gown', 'rental', 'wedding-bridal-items', 1, 1, '👰', 'Western bridal gowns & veils'),
  ('rental', 2, 'Lehenga', 'lehenga', 'rental', 'wedding-bridal-items', 1, 2, '👗', 'Bridal & reception lehengas'),
  ('rental', 2, 'Nilame & Groom Wear', 'nilame-groom-wear', 'rental', 'wedding-bridal-items', 1, 3, '👑', 'Traditional Kandyan Mul Anduma & sherwanis'),
  ('rental', 2, 'Bridal Jewellery', 'bridal-jewellery', 'rental', 'wedding-bridal-items', 1, 4, '💎', 'Gold plated sets, headpieces & bangles'),
  ('rental', 2, 'Wedding Accessories', 'wedding-accessories', 'rental', 'wedding-bridal-items', 1, 5, '👠', 'Tiara, shoes, bouquets & clutches'),
  ('rental', 1, 'Outdoor & Camping', 'outdoor-camping', NULL, NULL, NULL, 12, '⛺', 'Tents, sleeping bags, stoves, hiking gear & camping sets'),
  ('rental', 2, 'Camping Tent', 'camping-tent', 'rental', 'outdoor-camping', 1, 0, '⛺', '2, 4, 6 & 8 person waterproof tents'),
  ('rental', 2, 'Sleeping Bag & Mat', 'sleeping-bag-mat', 'rental', 'outdoor-camping', 1, 1, '🛌', 'Thermal sleeping bags & air mattresses'),
  ('rental', 2, 'Camping Chair & Table', 'camping-chair-table', 'rental', 'outdoor-camping', 1, 2, '🪑', 'Foldable lightweight furniture'),
  ('rental', 2, 'Camping Stove & Cookware', 'camping-stove-cookware', 'rental', 'outdoor-camping', 1, 3, '🍳', 'Butane portable stoves & mess kits'),
  ('rental', 2, 'Lantern & Headlamps', 'lantern-headlamps', 'rental', 'outdoor-camping', 1, 4, '🔦', 'Rechargeable LED camp lights'),
  ('rental', 2, 'Cooler Box & Ice Chest', 'cooler-box-ice-chest', 'rental', 'outdoor-camping', 1, 5, '🧊', 'Insulated ice boxes for trips'),
  ('rental', 2, 'Hiking Gear & Backpacks', 'hiking-gear-backpacks', 'rental', 'outdoor-camping', 1, 6, '🎒', 'Trekking poles & 60L-80L rucksacks'),
  ('rental', 2, 'BBQ Grill', 'bbq-grill', 'rental', 'outdoor-camping', 1, 7, '🍖', 'Charcoal & gas barbecue stands'),
  ('rental', 1, 'Sports & Fitness Equipment', 'sports-fitness-equipment', NULL, NULL, NULL, 13, '🏋️', 'Treadmills, exercise bikes, dumbbells, cricket & gym gear'),
  ('rental', 2, 'Treadmill', 'treadmill', 'rental', 'sports-fitness-equipment', 1, 0, '🏃', 'Motorized home & commercial treadmills'),
  ('rental', 2, 'Exercise Bike', 'exercise-bike', 'rental', 'sports-fitness-equipment', 1, 1, '🚴', 'Spin bikes & magnetic stationary cycles'),
  ('rental', 2, 'Dumbbells & Weights', 'dumbbells-weights', 'rental', 'sports-fitness-equipment', 1, 2, '🏋️', 'Barbells, plates & adjustable dumbbells'),
  ('rental', 2, 'Multi Gym Equipment', 'multi-gym-equipment', 'rental', 'sports-fitness-equipment', 1, 3, '🦾', 'Home gym benches, racks & pull-up towers'),
  ('rental', 2, 'Cricket Equipment', 'cricket-equipment', 'rental', 'sports-fitness-equipment', 1, 4, '🏏', 'Bats, pads, helmets, nets & bowling machines'),
  ('rental', 2, 'Badminton & Tennis', 'badminton-tennis', 'rental', 'sports-fitness-equipment', 1, 5, '🏸', 'Racquets, portable nets & shuttlecocks'),
  ('rental', 2, 'Surfing & Water Sports', 'surfing-water-sports', 'rental', 'sports-fitness-equipment', 1, 6, '🏄', 'Surfboards, bodyboards & paddleboards'),
  ('rental', 1, 'Baby & Kids Equipment', 'baby-kids-equipment', NULL, NULL, NULL, 14, '🍼', 'Strollers, baby cots, car seats, high chairs & kids party toys'),
  ('rental', 2, 'Baby Stroller / Pram', 'baby-stroller-pram', 'rental', 'baby-kids-equipment', 1, 0, '🛒', 'Foldable lightweight & travel strollers'),
  ('rental', 2, 'Baby Cot & Cradle', 'baby-cot-cradle', 'rental', 'baby-kids-equipment', 1, 1, '🛏️', 'Wooden & travel playpens with mattress'),
  ('rental', 2, 'Baby Car Seat', 'baby-car-seat', 'rental', 'baby-kids-equipment', 1, 2, '🪑', 'Infant & toddler safety seats'),
  ('rental', 2, 'High Chair & Booster', 'high-chair-booster', 'rental', 'baby-kids-equipment', 1, 3, '🪑', 'Feeding chairs with trays'),
  ('rental', 2, 'Baby Walker & Jumper', 'baby-walker-jumper', 'rental', 'baby-kids-equipment', 1, 4, '🚶', 'Activity walkers and rockers'),
  ('rental', 2, 'Kids Party Equipment', 'kids-party-equipment', 'rental', 'baby-kids-equipment', 1, 5, '🏰', 'Bouncy castles, soft play sets & mascots'),
  ('rental', 1, 'Medical & Mobility Equipment', 'medical-mobility-equipment', NULL, NULL, NULL, 15, '🩺', 'Wheelchairs, hospital beds, oxygen concentrators & patient aids'),
  ('rental', 2, 'Wheelchair', 'wheelchair', 'rental', 'medical-mobility-equipment', 1, 0, '🦽', 'Manual, lightweight & electric wheelchairs'),
  ('rental', 2, 'Hospital Bed', 'hospital-bed', 'rental', 'medical-mobility-equipment', 1, 1, '🛏️', 'Manual & motorized adjustable beds'),
  ('rental', 2, 'Oxygen Equipment', 'oxygen-equipment', 'rental', 'medical-mobility-equipment', 1, 2, '🫁', 'Oxygen concentrators & cylinders with regulator'),
  ('rental', 2, 'Walking Frame & Crutches', 'walking-frame-crutches', 'rental', 'medical-mobility-equipment', 1, 3, '🦯', 'Rollators, walkers & elbow crutches'),
  ('rental', 2, 'Commode Chair', 'commode-chair', 'rental', 'medical-mobility-equipment', 1, 4, '🪑', 'Bedside commodes & shower chairs'),
  ('rental', 2, 'Patient Lift & Hoist', 'patient-lift-hoist', 'rental', 'medical-mobility-equipment', 1, 5, '🦾', 'Hydraulic & electric patient transfer lifts'),
  ('rental', 1, 'Office Equipment', 'office-equipment', NULL, NULL, NULL, 16, '🖨️', 'Photocopiers, conference tech, shredders & office machinery'),
  ('rental', 2, 'Commercial Photocopier', 'commercial-photocopier', 'rental', 'office-equipment', 1, 0, '🖨️', 'Heavy duty A3/A4 network copiers'),
  ('rental', 2, 'Conference Tech', 'conference-tech', 'rental', 'office-equipment', 1, 1, '🎙️', 'Meeting owls, video soundbars & speakerphones'),
  ('rental', 2, 'Paper Shredder', 'paper-shredder', 'rental', 'office-equipment', 1, 2, '📄', 'Cross-cut heavy duty document shredders'),
  ('rental', 2, 'Laminator & Binding', 'laminator-binding', 'rental', 'office-equipment', 1, 3, '📑', 'Spiral & thermal binding machines'),
  ('rental', 1, 'Business & Commercial Equipment', 'business-commercial-equipment', NULL, NULL, NULL, 17, '💳', 'POS machines, barcode scanners, display stands & retail gear'),
  ('rental', 2, 'POS Machine', 'pos-machine', 'rental', 'business-commercial-equipment', 1, 0, '💳', 'Touchscreen POS terminals & thermal printers'),
  ('rental', 2, 'Barcode Scanner', 'barcode-scanner', 'rental', 'business-commercial-equipment', 1, 1, '📟', 'Handheld 1D/2D wireless scanners'),
  ('rental', 2, 'Cash Register & Drawer', 'cash-register-drawer', 'rental', 'business-commercial-equipment', 1, 2, '💵', 'Electronic cash drawers & counter boxes'),
  ('rental', 2, 'Display & Exhibition Stand', 'display-exhibition-stand', 'rental', 'business-commercial-equipment', 1, 3, '🖼️', 'Rollup banners, display racks & promo counters'),
  ('rental', 1, 'Agriculture & Farming Equipment', 'agriculture-farming-equipment', NULL, NULL, NULL, 18, '🌾', 'Tractors, grass cutters, power sprayers, tillers & farm tools'),
  ('rental', 2, 'Tractor & Attachments', 'tractor-attachments', 'rental', 'agriculture-farming-equipment', 1, 0, '🚜', '4WD tractors, rotavators & ploughs'),
  ('rental', 2, 'Grass & Brush Cutter', 'grass-brush-cutter', 'rental', 'agriculture-farming-equipment', 1, 1, '🌱', 'Petrol 2-stroke/4-stroke grass trimmers'),
  ('rental', 2, 'Power Sprayer', 'power-sprayer', 'rental', 'agriculture-farming-equipment', 1, 2, '💦', 'Knapsack & engine sprayers for fertilizer'),
  ('rental', 2, 'Power Tiller', 'power-tiller', 'rental', 'agriculture-farming-equipment', 1, 3, '⚙️', 'Hand tractor tillers for paddy & field'),
  ('rental', 2, 'Harvester', 'harvester', 'rental', 'agriculture-farming-equipment', 1, 4, '🌾', 'Combine harvesters & threshers'),
  ('rental', 2, 'Farming Hand Tools', 'farming-hand-tools', 'rental', 'agriculture-farming-equipment', 1, 5, '🛠️', 'Mammoties, pruning shears & augers'),
  ('rental', 1, 'Boats & Water Transport', 'boats-water-transport', NULL, NULL, NULL, 19, '⛵', 'Speedboats, fishing boats, yachts, kayaks & jet skis'),
  ('rental', 2, 'Speed Boat', 'speed-boat', 'rental', 'boats-water-transport', 1, 0, '🚤', 'Tour & passenger speedboats'),
  ('rental', 2, 'Fishing Boat', 'fishing-boat', 'rental', 'boats-water-transport', 1, 1, '🎣', 'Coastal and offshore crafts'),
  ('rental', 2, 'Yacht & Catamaran', 'yacht-catamaran', 'rental', 'boats-water-transport', 1, 2, '🛥️', 'Luxury sailing and sunset cruises'),
  ('rental', 2, 'Kayak & Canoe', 'kayak-canoe', 'rental', 'boats-water-transport', 1, 3, '🛶', 'Single & tandem recreational kayaks'),
  ('rental', 2, 'Jet Ski', 'jet-ski', 'rental', 'boats-water-transport', 1, 4, '🌊', 'High powered personal watercraft'),
  ('rental', 1, 'Travel & Luggage', 'travel-luggage', NULL, NULL, NULL, 20, '🧳', 'Suitcases, travel bags, roof racks & travel accessories'),
  ('rental', 2, 'Suitcase & Trolley Bags', 'suitcase-trolley-bags', 'rental', 'travel-luggage', 1, 0, '🧳', 'Large 28"-32" hard-shell suitcases'),
  ('rental', 2, 'Car Roof Box & Carrier', 'car-roof-box-carrier', 'rental', 'travel-luggage', 1, 1, '🚗', 'Universal roof luggage boxes'),
  ('rental', 2, 'Travel Accessories', 'travel-accessories', 'rental', 'travel-luggage', 1, 2, '🔌', 'Weighing scales, adaptors & covers'),
  ('rental', 1, 'Party & Entertainment Items', 'party-entertainment-items', NULL, NULL, NULL, 21, '🎈', 'Bouncy castles, karaoke machines, mascots & party games'),
  ('rental', 2, 'Bouncy Castle', 'bouncy-castle', 'rental', 'party-entertainment-items', 1, 0, '🏰', 'Inflatable castles and water slides'),
  ('rental', 2, 'Karaoke Machine', 'karaoke-machine', 'rental', 'party-entertainment-items', 1, 1, '🎤', 'Microphones, screen & song tracks'),
  ('rental', 2, 'Popcorn & Candy Floss Machine', 'popcorn-candy-floss-machine', 'rental', 'party-entertainment-items', 1, 2, '🍿', 'Party food stations'),
  ('rental', 2, 'Mascots & Costumes', 'mascots-costumes', 'rental', 'party-entertainment-items', 1, 3, '🎭', 'Cartoon & festival character suits'),
  ('rental', 1, 'Kitchen & Catering Equipment', 'kitchen-catering-equipment', NULL, NULL, NULL, 22, '🍳', 'Commercial cookers, chafing dishes, buffet sets & cutlery'),
  ('rental', 2, 'Chafing Dishes & Buffet Warmers', 'chafing-dishes-buffet-warmers', 'rental', 'kitchen-catering-equipment', 1, 0, '🍲', 'Stainless steel food warmers'),
  ('rental', 2, 'Plates, Glasses & Cutlery', 'plates-glasses-cutlery', 'rental', 'kitchen-catering-equipment', 1, 1, '🍽️', 'Dinnerware sets for large functions'),
  ('rental', 2, 'Commercial Burner & Stoves', 'commercial-burner-stoves', 'rental', 'kitchen-catering-equipment', 1, 2, '🔥', 'High pressure catering burners'),
  ('rental', 2, 'Beverage & Juice Dispensers', 'beverage-juice-dispensers', 'rental', 'kitchen-catering-equipment', 1, 3, '🧃', 'Cold drink & tea urn machines'),
  ('rental', 2, 'Catering BBQ Equipment', 'catering-bbq-equipment', 'rental', 'kitchen-catering-equipment', 1, 4, '🍖', 'Large function charcoal roasters'),
  ('rental', 1, 'Pet Equipment', 'pet-equipment', NULL, NULL, NULL, 23, '🐾', 'Pet cages, carriers, travel crates, strollers & grooming gear'),
  ('rental', 2, 'Pet Cage & Crate', 'pet-cage-crate', 'rental', 'pet-equipment', 1, 0, '🐕', 'Heavy duty steel & wire dog/cat cages'),
  ('rental', 2, 'Pet Carrier & Travel Box', 'pet-carrier-travel-box', 'rental', 'pet-equipment', 1, 1, '🐱', 'IATA airline approved travel carriers'),
  ('rental', 2, 'Pet Stroller', 'pet-stroller', 'rental', 'pet-equipment', 1, 2, '🛒', 'Wheeled strollers for dogs & cats'),
  ('rental', 2, 'Pet Grooming Equipment', 'pet-grooming-equipment', 'rental', 'pet-equipment', 1, 3, '✂️', 'Clippers, blowers & grooming tables'),
  ('rental', 2, 'Pet Training Equipment', 'pet-training-equipment', 'rental', 'pet-equipment', 1, 4, '🎾', 'Agility hurdles and leashes'),
  ('rental', 1, 'Musical Instruments & Audio', 'musical-instruments-audio', NULL, NULL, NULL, 24, '🎸', 'Guitars, keyboards, drum kits, DJ controllers & amplifiers'),
  ('rental', 2, 'Guitar', 'guitar', 'rental', 'musical-instruments-audio', 1, 0, '🎸', 'Acoustic, electric & bass guitars'),
  ('rental', 2, 'Keyboard & Piano', 'keyboard-piano', 'rental', 'musical-instruments-audio', 1, 1, '🎹', 'Yamaha, Roland keyboards & digital pianos'),
  ('rental', 2, 'Drum Set', 'drum-set', 'rental', 'musical-instruments-audio', 1, 2, '🥁', 'Acoustic drum kits & electronic drums'),
  ('rental', 2, 'Amplifier & Mixers', 'amplifier-mixers', 'rental', 'musical-instruments-audio', 1, 3, '📻', 'Marshall, Fender amps & audio mixers'),
  ('rental', 2, 'Traditional Instruments', 'traditional-instruments', 'rental', 'musical-instruments-audio', 1, 4, '🪘', 'Geta beraya, thammattama, tabla & violins'),
  ('rental', 1, 'Education & Study Equipment', 'education-study-equipment', NULL, NULL, NULL, 25, '📚', 'Whiteboards, podiums, science lab gear & classroom benches'),
  ('rental', 2, 'Whiteboard & Podium', 'whiteboard-podium', 'rental', 'education-study-equipment', 1, 0, '📋', 'Magnetic mobile whiteboards & lecterns'),
  ('rental', 2, 'Study Chairs & Desks', 'study-chairs-desks', 'rental', 'education-study-equipment', 1, 1, '🪑', 'Lecture hall chairs with writing pad'),
  ('rental', 2, 'Science & Lab Equipment', 'science-lab-equipment', 'rental', 'education-study-equipment', 1, 2, '🔬', 'Microscopes & educational models'),
  ('rental', 1, 'Other Rental Items', 'other-rental-items', NULL, NULL, NULL, 26, '📦', 'Miscellaneous specialty rental items and equipment'),
  ('rental', 2, 'General Rental Items', 'general-rental-items', 'rental', 'other-rental-items', 1, 0, '📦', 'Other items not listed above'),
  ('job', 1, 'Office & Administration', 'office-administration', NULL, NULL, NULL, 0, '📂', 'Office assistants, receptionists, data entry and secretarial roles'),
  ('job', 2, 'Office Assistant', 'office-assistant', 'job', 'office-administration', 1, 0, '📎', 'General clerical & office help'),
  ('job', 2, 'Receptionist', 'receptionist', 'job', 'office-administration', 1, 1, '🛎️', 'Front desk management & guest greeting'),
  ('job', 2, 'Data Entry Operator', 'data-entry-operator', 'job', 'office-administration', 1, 2, '⌨️', 'Typing, database entry & spreadsheet tasks'),
  ('job', 2, 'Clerk', 'clerk', 'job', 'office-administration', 1, 3, '📁', 'Documentation & administrative filing'),
  ('job', 2, 'Secretary', 'secretary', 'job', 'office-administration', 1, 4, '📝', 'Executive assistance & appointment scheduling'),
  ('job', 2, 'Administrative Assistant', 'administrative-assistant', 'job', 'office-administration', 1, 5, '📋', 'Operations support & office coordination'),
  ('job', 2, 'Personal Assistant (PA)', 'personal-assistant-pa', 'job', 'office-administration', 1, 6, '💼', 'Executive & direct director support'),
  ('job', 2, 'Document Controller', 'document-controller', 'job', 'office-administration', 1, 7, '📑', 'Archiving & project document management'),
  ('job', 2, 'Front Office Executive', 'front-office-executive', 'job', 'office-administration', 1, 8, '🏢', 'Customer greeting & desk administration'),
  ('job', 1, 'IT & Technology', 'it-technology', NULL, NULL, NULL, 1, '💻', 'Software engineers, web developers, mobile apps, QA & tech support'),
  ('job', 2, 'Software Developer', 'software-developer', 'job', 'it-technology', 1, 0, '💻', 'Backend, systems & application programming'),
  ('job', 2, 'Web Developer', 'web-developer', 'job', 'it-technology', 1, 1, '🌐', 'Website & web app development'),
  ('job', 2, 'Frontend Developer', 'frontend-developer', 'job', 'it-technology', 1, 2, '🎨', 'React, Vue, Angular UI development'),
  ('job', 2, 'Backend Developer', 'backend-developer', 'job', 'it-technology', 1, 3, '⚙️', 'Node.js, Python, Java, Go, APIs & databases'),
  ('job', 2, 'Full Stack Developer', 'full-stack-developer', 'job', 'it-technology', 1, 4, '🚀', 'End-to-end full stack web architecture'),
  ('job', 2, 'Mobile App Developer', 'mobile-app-developer', 'job', 'it-technology', 1, 5, '📱', 'iOS (Swift), Android (Kotlin), Flutter, React Native'),
  ('job', 2, 'UI/UX Designer', 'uiux-designer', 'job', 'it-technology', 1, 6, '✨', 'Figma wireframing & user experience design'),
  ('job', 2, 'QA Engineer', 'qa-engineer', 'job', 'it-technology', 1, 7, '🐞', 'Manual & automated quality assurance testing'),
  ('job', 2, 'Data Analyst / Scientist', 'data-analyst-scientist', 'job', 'it-technology', 1, 8, '📊', 'SQL, Python, PowerBI & machine learning'),
  ('job', 2, 'DevOps / Cloud Engineer', 'devops-cloud-engineer', 'job', 'it-technology', 1, 9, '☁️', 'AWS, GCP, Docker, Kubernetes & CI/CD'),
  ('job', 2, 'Network Engineer', 'network-engineer', 'job', 'it-technology', 1, 10, '📡', 'Cisco, routing, switches & firewall security'),
  ('job', 2, 'Cyber Security Specialist', 'cyber-security-specialist', 'job', 'it-technology', 1, 11, '🛡️', 'Penetration testing & vulnerability assessment'),
  ('job', 2, 'IT Support & Helpdesk', 'it-support-helpdesk', 'job', 'it-technology', 1, 12, '🛠️', 'Hardware troubleshooting, OS & network setup'),
  ('job', 1, 'Sales & Marketing', 'sales-marketing', NULL, NULL, NULL, 2, '📈', 'Sales executives, digital marketing, SEO, social media & brand management'),
  ('job', 2, 'Sales Executive', 'sales-executive', 'job', 'sales-marketing', 1, 0, '💼', 'B2B/B2C direct product & service sales'),
  ('job', 2, 'Sales Representative', 'sales-representative', 'job', 'sales-marketing', 1, 1, '🤝', 'Field sales, store representation & outreach'),
  ('job', 2, 'Marketing Executive', 'marketing-executive', 'job', 'sales-marketing', 1, 2, '📢', 'Campaign execution & promotional drives'),
  ('job', 2, 'Digital Marketing Executive', 'digital-marketing-executive', 'job', 'sales-marketing', 1, 3, '📱', 'PPC, performance ads & campaign manager'),
  ('job', 2, 'Social Media Manager', 'social-media-manager', 'job', 'sales-marketing', 1, 4, '💬', 'Instagram, TikTok, Facebook content & community'),
  ('job', 2, 'SEO Specialist', 'seo-specialist', 'job', 'sales-marketing', 1, 5, '🔍', 'Organic ranking, keywords & content audit'),
  ('job', 2, 'Content Creator', 'content-creator', 'job', 'sales-marketing', 1, 6, '🎬', 'Video reels, copywriting & digital media'),
  ('job', 2, 'Brand Executive', 'brand-executive', 'job', 'sales-marketing', 1, 7, '🌟', 'Brand strategy, PR & event activations'),
  ('job', 2, 'Telemarketing / Cold Caller', 'telemarketing-cold-caller', 'job', 'sales-marketing', 1, 8, '📞', 'Phone sales & inbound/outbound leads'),
  ('job', 1, 'Accounting & Finance', 'accounting-finance', NULL, NULL, NULL, 3, '📊', 'Accountants, auditors, bookkeepers, payroll and finance managers'),
  ('job', 2, 'Accountant', 'accountant', 'job', 'accounting-finance', 1, 0, '📊', 'Full financial accounts & tax compliance'),
  ('job', 2, 'Accounts Assistant', 'accounts-assistant', 'job', 'accounting-finance', 1, 1, '🧾', 'Ledger entry, invoicing & bank reconciliation'),
  ('job', 2, 'Auditor', 'auditor', 'job', 'accounting-finance', 1, 2, '🔍', 'Internal & external compliance auditing'),
  ('job', 2, 'Finance Manager / Executive', 'finance-manager-executive', 'job', 'accounting-finance', 1, 3, '💼', 'Financial planning & cost budgeting'),
  ('job', 2, 'Bookkeeper', 'bookkeeper', 'job', 'accounting-finance', 1, 4, '📒', 'QuickBooks, Xero & day-to-day accounts'),
  ('job', 2, 'Payroll Officer', 'payroll-officer', 'job', 'accounting-finance', 1, 5, '💳', 'EPF/ETF salary processing & disbursements'),
  ('job', 2, 'Tax Assistant', 'tax-assistant', 'job', 'accounting-finance', 1, 6, '📑', 'RAMIS VAT, SSCL & corporate tax filings'),
  ('job', 2, 'Cashier', 'cashier', 'job', 'accounting-finance', 1, 7, '💵', 'Point of sale, billing & cash handling'),
  ('job', 1, 'Banking & Insurance', 'banking-insurance', NULL, NULL, NULL, 4, '🏦', 'Bank officers, credit analysts, insurance agents and underwriting'),
  ('job', 2, 'Bank Officer / Trainee', 'bank-officer-trainee', 'job', 'banking-insurance', 1, 0, '🏦', 'Branch operations & customer servicing'),
  ('job', 2, 'Credit & Recovery Officer', 'credit-recovery-officer', 'job', 'banking-insurance', 1, 1, '💳', 'Loan approvals & credit verification'),
  ('job', 2, 'Insurance Advisor / Agent', 'insurance-advisor-agent', 'job', 'banking-insurance', 1, 2, '🛡️', 'Life & general insurance sales'),
  ('job', 2, 'Underwriter', 'underwriter', 'job', 'banking-insurance', 1, 3, '📋', 'Risk assessment & policy processing'),
  ('job', 1, 'Hospitality & Tourism', 'hospitality-tourism', NULL, NULL, NULL, 5, '🏨', 'Hotel managers, front office, waiters, housekeepers and tour guides'),
  ('job', 2, 'Hotel Manager', 'hotel-manager', 'job', 'hospitality-tourism', 1, 0, '🏨', 'Resort & hotel operations leadership'),
  ('job', 2, 'Hotel Receptionist / Front Desk', 'hotel-receptionist-front-desk', 'job', 'hospitality-tourism', 1, 1, '🛎️', 'Guest check-in & reservation handling'),
  ('job', 2, 'Waiter / Waitress', 'waiter-waitress', 'job', 'hospitality-tourism', 1, 2, '🍽️', 'Restaurant table service & steward duties'),
  ('job', 2, 'Chef / Cook', 'chef-cook', 'job', 'hospitality-tourism', 1, 3, '👨‍🍳', 'Executive chef, commis & kitchen cook'),
  ('job', 2, 'Kitchen Helper', 'kitchen-helper', 'job', 'hospitality-tourism', 1, 4, '🥣', 'Dishwashing, vegetable chopping & prep'),
  ('job', 2, 'Barista / Bartender', 'barista-bartender', 'job', 'hospitality-tourism', 1, 5, '☕', 'Coffee brewing & cocktail mixing'),
  ('job', 2, 'Housekeeping / Room Attendant', 'housekeeping-room-attendant', 'job', 'hospitality-tourism', 1, 6, '🧹', 'Room cleaning, bed making & linen care'),
  ('job', 2, 'Tour Guide / Travel Executive', 'tour-guide-travel-executive', 'job', 'hospitality-tourism', 1, 7, '🌴', 'SLTDA licensed tourist guides & coordinators'),
  ('job', 1, 'Food & Restaurant', 'food-restaurant', NULL, NULL, NULL, 6, '🍽️', 'Restaurant staff, bakery chefs, fast food crew and caterers'),
  ('job', 2, 'Restaurant Cook', 'restaurant-cook', 'job', 'food-restaurant', 1, 0, '🍳', 'Sri Lankan, Chinese & Western culinary cooks'),
  ('job', 2, 'Baker & Pastry Chef', 'baker-pastry-chef', 'job', 'food-restaurant', 1, 1, '🥐', 'Breads, cakes, pastries & desserts'),
  ('job', 2, 'Fast Food Crew Member', 'fast-food-crew-member', 'job', 'food-restaurant', 1, 2, '🍔', 'Burger, fried chicken & pizza counter staff'),
  ('job', 2, 'Kottu / Roti Master', 'kottu-roti-master', 'job', 'food-restaurant', 1, 3, '🥘', 'Specialist Sri Lankan kottu & hoppers'),
  ('job', 2, 'Restaurant Supervisor', 'restaurant-supervisor', 'job', 'food-restaurant', 1, 4, '📋', 'Floor management & staff coordination'),
  ('job', 1, 'Driving & Transport', 'driving-transport', NULL, NULL, NULL, 7, '🚗', 'Car drivers, van drivers, lorry drivers, couriers and forklift operators'),
  ('job', 2, 'Car Driver', 'car-driver', 'job', 'driving-transport', 1, 0, '🚗', 'Personal, corporate & VIP chauffeurs'),
  ('job', 2, 'Van Driver', 'van-driver', 'job', 'driving-transport', 1, 1, '🚐', 'School van, office transport & tour van'),
  ('job', 2, 'Lorry Driver', 'lorry-driver', 'job', 'driving-transport', 1, 2, '🚛', 'Heavy vehicle & light goods lorry drivers'),
  ('job', 2, 'Bus Driver', 'bus-driver', 'job', 'driving-transport', 1, 3, '🚌', 'Route bus & luxury coach drivers'),
  ('job', 2, 'Courier / Delivery Rider', 'courier-delivery-rider', 'job', 'driving-transport', 1, 4, '🛵', 'Food delivery & express package courier'),
  ('job', 2, 'Three Wheeler Driver', 'three-wheeler-driver', 'job', 'driving-transport', 1, 5, '🛺', 'Tuk-tuk hire & local transport'),
  ('job', 2, 'Forklift Operator', 'forklift-operator', 'job', 'driving-transport', 1, 6, '🚜', 'Warehouse container loading & pallet handling'),
  ('job', 1, 'Logistics & Warehouse', 'logistics-warehouse', NULL, NULL, NULL, 8, '📦', 'Store keepers, warehouse supervisors, dispatchers and stock controllers'),
  ('job', 2, 'Store Keeper', 'store-keeper', 'job', 'logistics-warehouse', 1, 0, '📦', 'Goods receiving, issuing & bin card records'),
  ('job', 2, 'Warehouse Supervisor', 'warehouse-supervisor', 'job', 'logistics-warehouse', 1, 1, '📋', 'Floor operations & worker management'),
  ('job', 2, 'Inventory / Stock Controller', 'inventory-stock-controller', 'job', 'logistics-warehouse', 1, 2, '📊', 'Audits, cycle counts & ERP updates'),
  ('job', 2, 'Dispatch & Logistics Officer', 'dispatch-logistics-officer', 'job', 'logistics-warehouse', 1, 3, '🚚', 'Route planning & transport coordination'),
  ('job', 1, 'Construction', 'construction', NULL, NULL, NULL, 9, '🏗️', 'Site supervisors, masons, carpenters, plumbers, electricians and painters'),
  ('job', 2, 'Site Supervisor', 'site-supervisor', 'job', 'construction', 1, 0, '👷', 'Civil construction execution & quality checks'),
  ('job', 2, 'Mason', 'mason', 'job', 'construction', 1, 1, '🧱', 'Bricklaying, plastering & foundation work'),
  ('job', 2, 'Carpenter', 'carpenter', 'job', 'construction', 1, 2, '🪚', 'Roofing, shuttering, doors & timber fittings'),
  ('job', 2, 'Electrician', 'electrician', 'job', 'construction', 1, 3, '⚡', 'Concealed wiring, panels & single/3-phase'),
  ('job', 2, 'Plumber', 'plumber', 'job', 'construction', 1, 4, '🚰', 'Water lines, drainage & sanitary ware fitting'),
  ('job', 2, 'Painter', 'painter', 'job', 'construction', 1, 5, '🎨', 'Interior/exterior wall painting & putty'),
  ('job', 2, 'Tile Worker', 'tile-worker', 'job', 'construction', 1, 6, '📐', 'Floor & wall tile fixing with precision cuts'),
  ('job', 2, 'Welder', 'welder', 'job', 'construction', 1, 7, '🔥', 'Steel fabrication, gates, grills & structural welding'),
  ('job', 2, 'Heavy Equipment Operator', 'heavy-equipment-operator', 'job', 'construction', 1, 8, '🚜', 'Excavator (JCB), crane & road roller operators'),
  ('job', 1, 'Engineering', 'engineering', NULL, NULL, NULL, 10, '⚙️', 'Civil, mechanical, electrical, QA engineers and quantity surveyors'),
  ('job', 2, 'Civil Engineer', 'civil-engineer', 'job', 'engineering', 1, 0, '🏛️', 'Structural design & project engineering'),
  ('job', 2, 'Mechanical Engineer', 'mechanical-engineer', 'job', 'engineering', 1, 1, '⚙️', 'HVAC, machinery & automotive engineering'),
  ('job', 2, 'Electrical Engineer', 'electrical-engineer', 'job', 'engineering', 1, 2, '⚡', 'High voltage, power systems & control units'),
  ('job', 2, 'Quantity Surveyor (QS)', 'quantity-surveyor-qs', 'job', 'engineering', 1, 3, '📐', 'BOQs, estimation, takeoff & cost control'),
  ('job', 2, 'Site Engineer', 'site-engineer', 'job', 'engineering', 1, 4, '🏗️', 'Day-to-day engineering on construction sites'),
  ('job', 1, 'Architecture & Design', 'architecture-design', NULL, NULL, NULL, 11, '📐', 'Architects, interior designers, draftsmen, 3D visualizers and landscape designers'),
  ('job', 2, 'Architect', 'architect', 'job', 'architecture-design', 1, 0, '🏛️', 'Residential & commercial architectural design'),
  ('job', 2, 'Interior Designer', 'interior-designer', 'job', 'architecture-design', 1, 1, '🛋️', 'Space planning, aesthetics & lighting design'),
  ('job', 2, 'Draftsman / CAD Operator', 'draftsman-cad-operator', 'job', 'architecture-design', 1, 2, '📐', 'AutoCAD, Revit 2D/3D council drawings'),
  ('job', 2, '3D Visualizer', '3d-visualizer', 'job', 'architecture-design', 1, 3, '🖥️', '3ds Max, Blender, SketchUp & Lumion renders'),
  ('job', 1, 'Factory & Manufacturing', 'factory-manufacturing', NULL, NULL, NULL, 12, '🏭', 'Machine operators, assembly workers, garment workers and QA controllers'),
  ('job', 2, 'Production Operator', 'production-operator', 'job', 'factory-manufacturing', 1, 0, '⚙️', 'Assembly line & general manufacturing tasks'),
  ('job', 2, 'Machine Operator', 'machine-operator', 'job', 'factory-manufacturing', 1, 1, '🎛️', 'Automated packaging, cutting & press machines'),
  ('job', 2, 'Packing Worker', 'packing-worker', 'job', 'factory-manufacturing', 1, 2, '📦', 'Boxing, labeling & packaging finished goods'),
  ('job', 2, 'Garment / Juki Operator', 'garment-juki-operator', 'job', 'factory-manufacturing', 1, 3, '🧵', 'Sewing machine operator & sample tailor'),
  ('job', 2, 'Quality Controller (QC)', 'quality-controller-qc', 'job', 'factory-manufacturing', 1, 4, '🔍', 'Defect inspection & standard testing'),
  ('job', 2, 'Production Supervisor', 'production-supervisor', 'job', 'factory-manufacturing', 1, 5, '📋', 'Shift management & output targets'),
  ('job', 1, 'Healthcare', 'healthcare', NULL, NULL, NULL, 13, '🩺', 'Doctors, nurses, pharmacists, caregivers, physiotherapists and lab technicians'),
  ('job', 2, 'Doctor / Medical Officer', 'doctor-medical-officer', 'job', 'healthcare', 1, 0, '👨‍⚕️', 'General physician, MBBS & clinic practice'),
  ('job', 2, 'Nurse', 'nurse', 'job', 'healthcare', 1, 1, '👩‍⚕️', 'Hospital, clinic & private duty nursing'),
  ('job', 2, 'Pharmacist / Pharmacy Assistant', 'pharmacist-pharmacy-assistant', 'job', 'healthcare', 1, 2, '💊', 'Dispensing prescriptions & inventory'),
  ('job', 2, 'Lab Technician', 'lab-technician', 'job', 'healthcare', 1, 3, '🔬', 'Blood tests, pathology & sample testing'),
  ('job', 2, 'Caregiver / Home Care', 'caregiver-home-care', 'job', 'healthcare', 1, 4, '👵', 'Elderly care & patient assistance'),
  ('job', 2, 'Physiotherapist', 'physiotherapist', 'job', 'healthcare', 1, 5, '🏃', 'Rehabilitation & physical recovery'),
  ('job', 2, 'Dental Assistant', 'dental-assistant', 'job', 'healthcare', 1, 6, '🦷', 'Dental surgery support & sterilization'),
  ('job', 1, 'Education', 'education', NULL, NULL, NULL, 14, '📚', 'School teachers, preschool teachers, lecturers, private tutors and trainers'),
  ('job', 2, 'Teacher', 'teacher', 'job', 'education', 1, 0, '👩‍🏫', 'Primary & secondary school educators'),
  ('job', 2, 'Preschool Teacher', 'preschool-teacher', 'job', 'education', 1, 1, '🧸', 'Early childhood education & Montessori'),
  ('job', 2, 'Lecturer', 'lecturer', 'job', 'education', 1, 2, '🎓', 'University & higher education institutes'),
  ('job', 2, 'Tutor', 'tutor', 'job', 'education', 1, 3, '📝', 'O/L, A/L and syllabus home tuition'),
  ('job', 2, 'English Teacher', 'english-teacher', 'job', 'education', 1, 4, '🗣️', 'Spoken English, IELTS & grammar'),
  ('job', 2, 'ICT / Computer Teacher', 'ict-computer-teacher', 'job', 'education', 1, 5, '💻', 'Programming & computer literacy'),
  ('job', 2, 'Science & Maths Teacher', 'science-maths-teacher', 'job', 'education', 1, 6, '📐', 'Mathematics, Physics & Chemistry'),
  ('job', 1, 'Beauty & Fashion', 'beauty-fashion', NULL, NULL, NULL, 15, '💇', 'Hairdressers, beauticians, barbers, makeup artists, tailors and designers'),
  ('job', 2, 'Beautician', 'beautician', 'job', 'beauty-fashion', 1, 0, '💆', 'Facials, skin treatments & threading'),
  ('job', 2, 'Hairdresser / Stylist', 'hairdresser-stylist', 'job', 'beauty-fashion', 1, 1, '✂️', 'Cutting, styling, coloring & rebonding'),
  ('job', 2, 'Barber', 'barber', 'job', 'beauty-fashion', 1, 2, '💈', 'Men’s haircuts, shaves & beard grooming'),
  ('job', 2, 'Makeup Artist', 'makeup-artist', 'job', 'beauty-fashion', 1, 3, '💄', 'Bridal & event makeup'),
  ('job', 2, 'Tailor / Dressmaker', 'tailor-dressmaker', 'job', 'beauty-fashion', 1, 4, '👗', 'Custom garment stitching & alterations'),
  ('job', 2, 'Fashion Designer', 'fashion-designer', 'job', 'beauty-fashion', 1, 5, '✨', 'Apparel concepts & pattern making'),
  ('job', 1, 'Security', 'security', NULL, NULL, NULL, 16, '🛡️', 'Security guards, CCTV operators, bodyguards and security officers'),
  ('job', 2, 'Security Guard', 'security-guard', 'job', 'security', 1, 0, '👮', 'Gate control, premises watch & day/night shifts'),
  ('job', 2, 'Security Officer / Supervisor', 'security-officer-supervisor', 'job', 'security', 1, 1, '🎖️', 'Shift commander & inspection'),
  ('job', 2, 'CCTV Operator', 'cctv-operator', 'job', 'security', 1, 2, '🖥️', 'Control room surveillance monitoring'),
  ('job', 2, 'Bodyguard / VIP Escort', 'bodyguard-vip-escort', 'job', 'security', 1, 3, '🕶️', 'Personal close protection officers'),
  ('job', 1, 'Cleaning & Maintenance', 'cleaning-maintenance', NULL, NULL, NULL, 17, '🧹', 'Janitors, housekeepers, office cleaners, gardeners and handy workers'),
  ('job', 2, 'Cleaner / Janitor', 'cleaner-janitor', 'job', 'cleaning-maintenance', 1, 0, '🧹', 'Office & commercial premises cleaning'),
  ('job', 2, 'Housekeeper', 'housekeeper', 'job', 'cleaning-maintenance', 1, 1, '🏠', 'Domestic home cooking & cleaning'),
  ('job', 2, 'Gardener', 'gardener', 'job', 'cleaning-maintenance', 1, 2, '🌱', 'Lawn mowing, tree trimming & plant care'),
  ('job', 2, 'Maintenance Worker', 'maintenance-worker', 'job', 'cleaning-maintenance', 1, 3, '🛠️', 'General handyman repairs & upkeep'),
  ('job', 1, 'Agriculture', 'agriculture', NULL, NULL, NULL, 18, '🌾', 'Farm workers, estate supervisors, tea pluckers and greenhouse staff'),
  ('job', 2, 'Farm Worker', 'farm-worker', 'job', 'agriculture', 1, 0, '🌾', 'Cultivation, harvesting & field labour'),
  ('job', 2, 'Estate Supervisor / Field Officer', 'estate-supervisor-field-officer', 'job', 'agriculture', 1, 1, '📋', 'Plantation & tea/coconut estate oversight'),
  ('job', 2, 'Dairy & Poultry Worker', 'dairy-poultry-worker', 'job', 'agriculture', 1, 2, '🐄', 'Animal feeding, egg collection & milking'),
  ('job', 1, 'Retail', 'retail', NULL, NULL, NULL, 19, '🛍️', 'Shop assistants, retail cashiers, visual merchandisers and store managers'),
  ('job', 2, 'Shop Assistant', 'shop-assistant', 'job', 'retail', 1, 0, '🛍️', 'Customer greeting, shelving & item packing'),
  ('job', 2, 'Retail Cashier', 'retail-cashier', 'job', 'retail', 1, 1, '💳', 'Supermarket billing & barcode scanning'),
  ('job', 2, 'Store Manager', 'store-manager', 'job', 'retail', 1, 2, '🏬', 'Retail outlet management & sales targets'),
  ('job', 2, 'Merchandiser', 'merchandiser', 'job', 'retail', 1, 3, '📦', 'Shelf display & stock replenishment'),
  ('job', 1, 'Customer Service', 'customer-service', NULL, NULL, NULL, 20, '🎧', 'Call center agents, customer support executives and helpdesk reps'),
  ('job', 2, 'Call Center Agent', 'call-center-agent', 'job', 'customer-service', 1, 0, '🎧', 'Inbound & outbound voice customer support'),
  ('job', 2, 'Customer Care Executive', 'customer-care-executive', 'job', 'customer-service', 1, 1, '💬', 'Resolving complaints & email tickets'),
  ('job', 2, 'Live Chat Agent', 'live-chat-agent', 'job', 'customer-service', 1, 2, '📱', 'Web chat & WhatsApp support specialist'),
  ('job', 1, 'Human Resources', 'human-resources', NULL, NULL, NULL, 21, '👥', 'HR managers, recruitment executives, talent scouts and training officers'),
  ('job', 2, 'HR Executive', 'hr-executive', 'job', 'human-resources', 1, 0, '📋', 'Employee records, attendance & onboarding'),
  ('job', 2, 'Recruiter / Talent Acquisition', 'recruiter-talent-acquisition', 'job', 'human-resources', 1, 1, '🔍', 'Sourcing, screening & interviewing candidates'),
  ('job', 2, 'HR Manager', 'hr-manager', 'job', 'human-resources', 1, 2, '💼', 'Labour law, company policy & performance'),
  ('job', 1, 'Legal', 'legal', NULL, NULL, NULL, 22, '⚖️', 'Lawyers, legal apprentices, compliance officers and legal secretaries'),
  ('job', 2, 'Lawyer / Attorney-at-Law', 'lawyer-attorney-at-law', 'job', 'legal', 1, 0, '⚖️', 'Corporate & litigation legal counsel'),
  ('job', 2, 'Legal Officer', 'legal-officer', 'job', 'legal', 1, 1, '📑', 'Contract drafting, vetting & compliance'),
  ('job', 2, 'Legal Assistant / Secretary', 'legal-assistant-secretary', 'job', 'legal', 1, 2, '📁', 'Filing, court documents & case research'),
  ('job', 1, 'Media & Creative', 'media-creative', NULL, NULL, NULL, 23, '🎬', 'Photographers, videographers, video editors, graphic designers and animators'),
  ('job', 2, 'Photographer', 'photographer', 'job', 'media-creative', 1, 0, '📷', 'Studio, fashion, product & event photography'),
  ('job', 2, 'Videographer', 'videographer', 'job', 'media-creative', 1, 1, '🎥', 'Camera operator, commercial & docu shoots'),
  ('job', 2, 'Video Editor', 'video-editor', 'job', 'media-creative', 1, 2, '✂️', 'Premiere Pro, After Effects, DaVinci editing'),
  ('job', 2, 'Graphic Designer', 'graphic-designer', 'job', 'media-creative', 1, 3, '🎨', 'Photoshop, Illustrator, social posts & logos'),
  ('job', 2, 'Animator', 'animator', 'job', 'media-creative', 1, 4, '✨', '2D/3D character animation & motion graphics'),
  ('job', 2, 'Voice Artist / Presenter', 'voice-artist-presenter', 'job', 'media-creative', 1, 5, '🎙️', 'Commercial dubbing & TV/radio presenting'),
  ('job', 1, 'Digital & Online Work', 'digital-online-work', NULL, NULL, NULL, 24, '🌐', 'E-commerce managers, virtual assistants, online researchers and mod teams'),
  ('job', 2, 'E-Commerce Manager', 'e-commerce-manager', 'job', 'digital-online-work', 1, 0, '🛒', 'Daraz, Shopify & WooCommerce operations'),
  ('job', 2, 'Community Moderator', 'community-moderator', 'job', 'digital-online-work', 1, 1, '🛡️', 'Forum, Discord & Facebook group moderation'),
  ('job', 2, 'Virtual Assistant', 'virtual-assistant', 'job', 'digital-online-work', 1, 2, '💻', 'Email management, research & calendar handling'),
  ('job', 1, 'Freelance & Remote', 'freelance-remote', NULL, NULL, NULL, 25, '🏠', 'Remote developers, freelance writers, translators and global contract roles'),
  ('job', 2, 'Freelance Developer', 'freelance-developer', 'job', 'freelance-remote', 1, 0, '💻', 'Remote contract programming jobs'),
  ('job', 2, 'Content Writer / Copywriter', 'content-writer-copywriter', 'job', 'freelance-remote', 1, 1, '✍️', 'Articles, blogs, SEO copywriting'),
  ('job', 2, 'Translator', 'translator', 'job', 'freelance-remote', 1, 2, '🗣️', 'Sinhala, Tamil, English translations'),
  ('job', 2, 'Remote Customer Support', 'remote-customer-support', 'job', 'freelance-remote', 1, 3, '🎧', 'Global timezone chat & email tickets'),
  ('job', 1, 'Business Development', 'business-development', NULL, NULL, NULL, 26, '🤝', 'BD executives, partnership leads and enterprise sales coordinators'),
  ('job', 2, 'Business Development Executive', 'business-development-executive', 'job', 'business-development', 1, 0, '💼', 'B2B outreach & corporate partnership deals'),
  ('job', 2, 'Key Account Manager', 'key-account-manager', 'job', 'business-development', 1, 1, '🌟', 'Client relationship retention & expansion'),
  ('job', 1, 'Management', 'management', NULL, NULL, NULL, 27, '👔', 'General managers, operations directors, branch heads and project leads'),
  ('job', 2, 'General Manager (GM)', 'general-manager-gm', 'job', 'management', 1, 0, '👔', 'Company-wide business strategy & profitability'),
  ('job', 2, 'Operations Manager', 'operations-manager', 'job', 'management', 1, 1, '⚙️', 'Process efficiency, team leadership & SLA'),
  ('job', 2, 'Branch Manager', 'branch-manager', 'job', 'management', 1, 2, '🏢', 'Regional branch staff & revenue management'),
  ('job', 2, 'Project Manager', 'project-manager', 'job', 'management', 1, 3, '📊', 'Timeline, sprint planning & milestone delivery'),
  ('job', 1, 'Government / Public Sector', 'government-public-sector', NULL, NULL, NULL, 28, '🏛️', 'Public sector vacancies, state corporation roles and municipal openings'),
  ('job', 2, 'State Clerical & Admin', 'state-clerical-admin', 'job', 'government-public-sector', 1, 0, '🏛️', 'Ministry & department administration'),
  ('job', 2, 'Public Service Executive', 'public-service-executive', 'job', 'government-public-sector', 1, 1, '📋', 'Officers in state statutory bodies'),
  ('job', 1, 'Other Jobs', 'other-jobs', NULL, NULL, NULL, 29, '💼', 'Miscellaneous job roles and specialized professions'),
  ('job', 2, 'General Vacancies', 'general-vacancies', 'job', 'other-jobs', 1, 0, '💼', 'Other job roles not listed above'),
  ('service', 1, 'Home Services', 'home-services', NULL, NULL, NULL, 0, '🏠', 'Plumbing, electrical, carpentry, painting, gardening, pest control & handyman'),
  ('service', 2, 'Plumbing', 'plumbing', 'service', 'home-services', 1, 0, '🚰', 'Pipe leaks, taps, pumps & drainage fixes'),
  ('service', 2, 'Electrical', 'electrical', 'service', 'home-services', 1, 1, '⚡', 'House wiring, switches, trips & lighting'),
  ('service', 2, 'Carpentry', 'carpentry', 'service', 'home-services', 1, 2, '🪚', 'Door fitting, lock repairs & timber woodwork'),
  ('service', 2, 'Painting', 'painting', 'service', 'home-services', 1, 3, '🎨', 'Wall painting, weather-shield & interior putty'),
  ('service', 2, 'Masonry', 'masonry', 'service', 'home-services', 1, 4, '🧱', 'Plastering, brickwork, floor leveling & repairs'),
  ('service', 2, 'Tile Work', 'tile-work', 'service', 'home-services', 1, 5, '📐', 'Tile laying, re-grouting & bathroom tiling'),
  ('service', 2, 'Roofing', 'roofing', 'service', 'home-services', 1, 6, '🏠', 'Roof leak sealing, gutters & ceiling repairs'),
  ('service', 2, 'Gardening & Landscaping', 'gardening-landscaping', 'service', 'home-services', 1, 7, '🌱', 'Lawn mowing, tree trimming & garden design'),
  ('service', 2, 'Pest Control', 'pest-control', 'service', 'home-services', 1, 8, '🐜', 'Termite (weyo), bedbug & rodent eradication'),
  ('service', 2, 'Handyman', 'handyman', 'service', 'home-services', 1, 9, '🛠️', 'Quick domestic fixes, drilling & wall mounting'),
  ('service', 2, 'Furniture Repair', 'furniture-repair', 'service', 'home-services', 1, 10, '🛋️', 'Couch reupholstering, polish & cane repair'),
  ('service', 2, 'CCTV Installation', 'cctv-installation', 'service', 'home-services', 1, 11, '📹', 'Home camera security setup & mobile view'),
  ('service', 2, 'Solar Installation', 'solar-installation', 'service', 'home-services', 1, 12, '☀️', 'Rooftop on-grid/off-grid solar systems'),
  ('service', 2, 'Water Tank Cleaning', 'water-tank-cleaning', 'service', 'home-services', 1, 13, '💧', 'Overhead & underground sump tank sanitation'),
  ('service', 1, 'Home Appliance Repair', 'home-appliance-repair', NULL, NULL, NULL, 1, '🧊', 'Fridges, washing machines, microwaves, TVs, ovens & small appliance repair'),
  ('service', 2, 'Refrigerator Repair', 'refrigerator-repair', 'service', 'home-appliance-repair', 1, 0, '🧊', 'Gas recharging, cooling issues & thermostats'),
  ('service', 2, 'Washing Machine Repair', 'washing-machine-repair', 'service', 'home-appliance-repair', 1, 1, '🧺', 'Motor, PCB board, drum & water drainage fix'),
  ('service', 2, 'AC Repair & Service', 'ac-repair-service', 'service', 'home-appliance-repair', 1, 2, '❄️', 'Filter cleaning, gas filling & compressor fixes'),
  ('service', 2, 'TV Repair', 'tv-repair', 'service', 'home-appliance-repair', 1, 3, '📺', 'LED/LCD display backlight, motherboard & sound'),
  ('service', 2, 'Microwave Repair', 'microwave-repair', 'service', 'home-appliance-repair', 1, 4, '🍲', 'Heating magnetron, turntable & electrical fixes'),
  ('service', 2, 'Cooker / Stove Repair', 'cooker-stove-repair', 'service', 'home-appliance-repair', 1, 5, '🍳', 'Gas leakage, burner clogging & induction repair'),
  ('service', 2, 'Water Heater Repair', 'water-heater-repair', 'service', 'home-appliance-repair', 1, 6, '🚿', 'Geyser element replacement & thermostat repair'),
  ('service', 2, 'Small Appliance Repair', 'small-appliance-repair', 'service', 'home-appliance-repair', 1, 7, '🔌', 'Blenders, irons, rice cookers & vacuum cleaners'),
  ('service', 1, 'Electrical Services', 'electrical-services', NULL, NULL, NULL, 2, '⚡', 'House wiring, 3-phase upgrades, generator servicing & panel boards'),
  ('service', 2, 'House & Building Wiring', 'house-building-wiring', 'service', 'electrical-services', 1, 0, '⚡', 'New wiring, renovations & conduit work'),
  ('service', 2, 'Breaker & Panel Board Fix', 'breaker-panel-board-fix', 'service', 'electrical-services', 1, 1, '🎛️', 'RCCB trips, main switches & distribution boards'),
  ('service', 2, 'Generator Repair & Service', 'generator-repair-service', 'service', 'electrical-services', 1, 2, '⚙️', 'Standby diesel & petrol generator maintenance'),
  ('service', 2, 'Lighting & Fan Installation', 'lighting-fan-installation', 'service', 'electrical-services', 1, 3, '💡', 'Chandeliers, downlights & ceiling fans'),
  ('service', 1, 'Plumbing Services', 'plumbing-services', NULL, NULL, NULL, 3, '🚰', 'Leak detection, bathroom fittings, motor pumps and gully clearance'),
  ('service', 2, 'Leak Detection & Pipe Repair', 'leak-detection-pipe-repair', 'service', 'plumbing-services', 1, 0, '💧', 'Concealed pipe leaks & burst line repair'),
  ('service', 2, 'Bathroom & Sanitary Fitting', 'bathroom-sanitary-fitting', 'service', 'plumbing-services', 1, 1, '🚿', 'Commodes, sinks, showers & mixer taps'),
  ('service', 2, 'Water Pump Repair & Fitting', 'water-pump-repair-fitting', 'service', 'plumbing-services', 1, 2, '⚙️', 'Pressure pumps, auto switches & motors'),
  ('service', 2, 'Drain & Gully Unblocking', 'drain-gully-unblocking', 'service', 'plumbing-services', 1, 3, '🕳️', 'Sewerage line unblocking & gully service'),
  ('service', 1, 'AC & Refrigeration', 'ac-refrigeration', NULL, NULL, NULL, 4, '❄️', 'Air conditioning cleaning, installation, gas charging & cold room service'),
  ('service', 2, 'AC Cleaning & General Service', 'ac-cleaning-general-service', 'service', 'ac-refrigeration', 1, 0, '❄️', 'Chemical wash, blower cleaning & efficiency tune'),
  ('service', 2, 'AC Installation & Relocation', 'ac-installation-relocation', 'service', 'ac-refrigeration', 1, 1, '🛠️', 'New AC mounting & shifting between rooms'),
  ('service', 2, 'AC Gas Charging', 'ac-gas-charging', 'service', 'ac-refrigeration', 1, 2, '💨', 'R32, R410A refrigerant top-up & leak testing'),
  ('service', 2, 'Commercial Cold Room Service', 'commercial-cold-room-service', 'service', 'ac-refrigeration', 1, 3, '🏢', 'Walk-in chillers, supermarket freezers'),
  ('service', 1, 'Cleaning Services', 'cleaning-services', NULL, NULL, NULL, 5, '🧹', 'Deep house cleaning, sofa shampooing, water tank & commercial janitorial'),
  ('service', 2, 'Deep House Cleaning', 'deep-house-cleaning', 'service', 'cleaning-services', 1, 0, '🏠', 'Move-in/move-out full home scrubbing & disinfection'),
  ('service', 2, 'Sofa & Carpet Shampooing', 'sofa-carpet-shampooing', 'service', 'cleaning-services', 1, 1, '🛋️', 'Fabric/leather steam cleaning & stain extraction'),
  ('service', 2, 'Commercial & Office Cleaning', 'commercial-office-cleaning', 'service', 'cleaning-services', 1, 2, '🏢', 'Daily/weekly office janitorial maintenance'),
  ('service', 2, 'Glass & Facade Cleaning', 'glass-facade-cleaning', 'service', 'cleaning-services', 1, 3, '🪟', 'High-rise windows & exterior facade washing'),
  ('service', 1, 'Vehicle Services', 'vehicle-services', NULL, NULL, NULL, 6, '🚗', 'Car repair, mobile mechanic, AC repair, detailing, wash & towing breakdown'),
  ('service', 2, 'Car Repair & Mechanical', 'car-repair-mechanical', 'service', 'vehicle-services', 1, 0, '🚗', 'Engine tune-up, brake service & suspension'),
  ('service', 2, 'Motorcycle & Scooter Repair', 'motorcycle-scooter-repair', 'service', 'vehicle-services', 1, 1, '🏍️', 'Bike tuning, engine overhaul & oil changes'),
  ('service', 2, 'Three Wheeler Repair', 'three-wheeler-repair', 'service', 'vehicle-services', 1, 2, '🛺', 'Tuk-tuk tuning, 2-stroke/4-stroke servicing'),
  ('service', 2, 'Auto Electrical & Battery', 'auto-electrical-battery', 'service', 'vehicle-services', 1, 3, '⚡', 'Starter motors, alternators & battery jumping'),
  ('service', 2, 'Vehicle AC Repair', 'vehicle-ac-repair', 'service', 'vehicle-services', 1, 4, '❄️', 'Car AC gas charging, condenser & compressor fix'),
  ('service', 2, 'Car Wash & Detailing', 'car-wash-detailing', 'service', 'vehicle-services', 1, 5, '✨', 'Ceramic coating, cut & polish, interior shampoo'),
  ('service', 2, 'Towing & Roadside Breakdown', 'towing-roadside-breakdown', 'service', 'vehicle-services', 1, 6, '🛻', '24/7 flatbed recovery & breakdown assistance'),
  ('service', 2, 'Tyre & Wheel Alignment', 'tyre-wheel-alignment', 'service', 'vehicle-services', 1, 7, '🛞', 'Puncture repair, wheel balancing & tyre replacement'),
  ('service', 1, 'Computer & Mobile', 'computer-mobile', NULL, NULL, NULL, 7, '💻', 'Laptop repair, mobile screen replacement, data recovery & software setup'),
  ('service', 2, 'Laptop Repair', 'laptop-repair', 'service', 'computer-mobile', 1, 0, '💻', 'Motherboard chip-level fix, display & hinges'),
  ('service', 2, 'Desktop PC Repair', 'desktop-pc-repair', 'service', 'computer-mobile', 1, 1, '🖥️', 'Hardware upgrades, power supply & custom builds'),
  ('service', 2, 'Mobile Phone Repair', 'mobile-phone-repair', 'service', 'computer-mobile', 1, 2, '📱', 'Display screen, battery & charging port replacement'),
  ('service', 2, 'Printer Repair & Ink Refill', 'printer-repair-ink-refill', 'service', 'computer-mobile', 1, 3, '🖨️', 'Head cleaning, roller jam & toner cartridge refill'),
  ('service', 2, 'Data Recovery', 'data-recovery', 'service', 'computer-mobile', 1, 4, '💾', 'Corrupted hard drives, SSDs & memory cards'),
  ('service', 2, 'Software & OS Installation', 'software-os-installation', 'service', 'computer-mobile', 1, 5, '💿', 'Windows 11/10, macOS, antivirus & drivers'),
  ('service', 2, 'WiFi & Network Setup', 'wifi-network-setup', 'service', 'computer-mobile', 1, 6, '📡', 'Office LAN cabling, router & mesh WiFi configuration'),
  ('service', 1, 'Business Services', 'business-services', NULL, NULL, NULL, 8, '💼', 'Company registration, HR, recruitment, office support and consulting'),
  ('service', 2, 'Company Registration (PVT LTD)', 'company-registration-pvt-ltd', 'service', 'business-services', 1, 0, '🏛️', 'ROC incorporation, Form 1 & bank account support'),
  ('service', 2, 'Business Consulting', 'business-consulting', 'service', 'business-services', 1, 1, '📊', 'Strategy, market research & feasibility studies'),
  ('service', 2, 'Recruitment & HR Services', 'recruitment-hr-services', 'service', 'business-services', 1, 2, '👥', 'Staff headhunting, payroll & HR management'),
  ('service', 2, 'Translation Services', 'translation-services', 'service', 'business-services', 1, 3, '🗣️', 'Sworn & certified English/Sinhala/Tamil translation'),
  ('service', 2, 'Document & Tender Preparation', 'document-tender-preparation', 'service', 'business-services', 1, 4, '📑', 'Business plans, profiles & project proposals'),
  ('service', 1, 'Digital Services', 'digital-services', NULL, NULL, NULL, 9, '🌐', 'Web development, mobile apps, SEO, digital marketing & Google Ads'),
  ('service', 2, 'Web Development', 'web-development', 'service', 'digital-services', 1, 0, '🌐', 'Custom business websites & corporate web apps'),
  ('service', 2, 'E-Commerce Website Setup', 'e-commerce-website-setup', 'service', 'digital-services', 1, 1, '🛒', 'Shopify, WooCommerce, Payment Gateway (PayHere)'),
  ('service', 2, 'Mobile App Development', 'mobile-app-development', 'service', 'digital-services', 1, 2, '📱', 'iOS & Android custom native/Flutter mobile apps'),
  ('service', 2, 'SEO (Search Engine Optimization)', 'seo-search-engine-optimization', 'service', 'digital-services', 1, 3, '🔍', 'Rank #1 on Google search results in Sri Lanka'),
  ('service', 2, 'Social Media Management', 'social-media-management', 'service', 'digital-services', 1, 4, '💬', 'Meta ads, Instagram & TikTok organic growth'),
  ('service', 2, 'Google & YouTube Ads', 'google-youtube-ads', 'service', 'digital-services', 1, 5, '📢', 'Targeted pay-per-click search & display campaigns'),
  ('service', 1, 'Creative Services', 'creative-services', NULL, NULL, NULL, 10, '🎨', 'Graphic design, logo design, video editing, branding and animation'),
  ('service', 2, 'Logo & Brand Identity', 'logo-brand-identity', 'service', 'creative-services', 1, 0, '✨', 'Unique vector logos, brand manuals & stationery'),
  ('service', 2, 'Graphic Design', 'graphic-design', 'service', 'creative-services', 1, 1, '🎨', 'Flyers, brochures, social posts & packaging'),
  ('service', 2, 'UI/UX Design', 'uiux-design', 'service', 'creative-services', 1, 2, '📱', 'Mobile app and web screen wireframes (Figma)'),
  ('service', 2, 'Video Editing', 'video-editing', 'service', 'creative-services', 1, 3, '✂️', 'YouTube videos, reels, commercials & colour grading'),
  ('service', 2, 'Animation & Motion Graphics', 'animation-motion-graphics', 'service', 'creative-services', 1, 4, '🎬', '2D explainer videos, intro animations & 3D logos'),
  ('service', 2, 'Content & Copywriting', 'content-copywriting', 'service', 'creative-services', 1, 5, '✍️', 'Compelling website copy, blogs & sales letters'),
  ('service', 1, 'Photography & Videography', 'photography-videography', NULL, NULL, NULL, 11, '📷', 'Wedding photography, event shoots, product photography & drone shoots'),
  ('service', 2, 'Wedding Photography', 'wedding-photography', 'service', 'photography-videography', 1, 0, '💒', 'Pre-shoots, wedding albums & bridal portraiture'),
  ('service', 2, 'Event Photography', 'event-photography', 'service', 'photography-videography', 1, 1, '📸', 'Birthdays, corporate events & convocation shoots'),
  ('service', 2, 'Product & Food Photography', 'product-food-photography', 'service', 'photography-videography', 1, 2, '🛍️', 'E-commerce studio photos & restaurant menus'),
  ('service', 2, 'Wedding Videography', 'wedding-videography', 'service', 'photography-videography', 1, 3, '🎥', 'Cinematic wedding trailers & full coverage'),
  ('service', 2, 'Drone Photography & Video', 'drone-photography-video', 'service', 'photography-videography', 1, 4, '🛸', '4K aerial shoots for land, villas & events'),
  ('service', 2, 'Photo Editing & Album Design', 'photo-editing-album-design', 'service', 'photography-videography', 1, 5, '🖼️', 'Skin retouching, background removal & album printing'),
  ('service', 1, 'Education & Tutoring', 'education-tutoring', NULL, NULL, NULL, 12, '📚', 'Maths, science, English, music, ICT and language private classes'),
  ('service', 2, 'Maths Tuition', 'maths-tuition', 'service', 'education-tutoring', 1, 0, '📐', 'Grade 6-11 O/L & Combined Maths A/L'),
  ('service', 2, 'Science Tuition', 'science-tuition', 'service', 'education-tutoring', 1, 1, '🔬', 'O/L Science, A/L Physics, Chemistry & Biology'),
  ('service', 2, 'English & IELTS Classes', 'english-ielts-classes', 'service', 'education-tutoring', 1, 2, '🗣️', 'Spoken English, grammar & IELTS preparation'),
  ('service', 2, 'ICT & Coding Classes', 'ict-coding-classes', 'service', 'education-tutoring', 1, 3, '💻', 'School ICT syllabus & Python/Web programming'),
  ('service', 2, 'Accounting & Commerce Tuition', 'accounting-commerce-tuition', 'service', 'education-tutoring', 1, 4, '📊', 'O/L & A/L Business studies & accounting'),
  ('service', 2, 'Music & Instrument Lessons', 'music-instrument-lessons', 'service', 'education-tutoring', 1, 5, '🎸', 'Guitar, keyboard, violin & vocal training'),
  ('service', 2, 'Foreign Language Classes', 'foreign-language-classes', 'service', 'education-tutoring', 1, 6, '🌍', 'Korean (EPS), Japanese (JLPT), French, Tamil'),
  ('service', 1, 'Event Services', 'event-services', NULL, NULL, NULL, 13, '🎉', 'Event planning, wedding coordinators, DJ, sound, catering & decoration'),
  ('service', 2, 'Event & Wedding Planning', 'event-wedding-planning', 'service', 'event-services', 1, 0, '📋', 'Full coordination, vendor management & scheduling'),
  ('service', 2, 'Decorations & Stage Setup', 'decorations-stage-setup', 'service', 'event-services', 1, 1, '💐', 'Theme backdrops, floral poruwa & balloon arches'),
  ('service', 2, 'DJ & Sound System Service', 'dj-sound-system-service', 'service', 'event-services', 1, 2, '🎧', 'Club/wedding DJs with bass lighting setups'),
  ('service', 2, 'Catering & Buffet Service', 'catering-buffet-service', 'service', 'event-services', 1, 3, '🍽️', 'Rice & curry, fried rice, BBQ & dessert buffets'),
  ('service', 2, 'Cake Making & Pastries', 'cake-making-pastries', 'service', 'event-services', 1, 4, '🎂', 'Wedding structures, birthday & customized fondant cakes'),
  ('service', 2, 'MC & Announcer', 'mc-announcer', 'service', 'event-services', 1, 5, '🎙️', 'Bilingual masters of ceremony (Sinhala/English/Tamil)'),
  ('service', 1, 'Beauty & Personal Care', 'beauty-personal-care', NULL, NULL, NULL, 14, '💇', 'Haircuts, bridal makeup, nail art, facials, massage & mehendi'),
  ('service', 2, 'Haircut & Styling', 'haircut-styling', 'service', 'beauty-personal-care', 1, 0, '✂️', 'Gents & ladies haircuts, rebonding & keratin'),
  ('service', 2, 'Bridal Dressing & Makeup', 'bridal-dressing-makeup', 'service', 'beauty-personal-care', 1, 1, '💄', 'Kandyan, Indian & Western bridal dressing'),
  ('service', 2, 'Facial & Skin Treatments', 'facial-skin-treatments', 'service', 'beauty-personal-care', 1, 2, '💆', 'Gold facials, cleanup, acne & skin brightening'),
  ('service', 2, 'Nail Art & Pedicure', 'nail-art-pedicure', 'service', 'beauty-personal-care', 1, 3, '💅', 'Gel nails, acrylic extensions & foot spa'),
  ('service', 2, 'Mehendi & Henna Art', 'mehendi-henna-art', 'service', 'beauty-personal-care', 1, 4, '✨', 'Intricate bridal & party henna patterns'),
  ('service', 2, 'Home Salon Service', 'home-salon-service', 'service', 'beauty-personal-care', 1, 5, '🏠', 'Doorstep beauty services for ladies'),
  ('service', 1, 'Health & Wellness', 'health-wellness', NULL, NULL, NULL, 15, '🧘', 'Personal fitness trainers, yoga, home nursing, physiotherapy & wellness'),
  ('service', 2, 'Personal Trainer & Fitness Coach', 'personal-trainer-fitness-coach', 'service', 'health-wellness', 1, 0, '🏋️', 'Weight loss, muscle gain & home workouts'),
  ('service', 2, 'Yoga Instructor', 'yoga-instructor', 'service', 'health-wellness', 1, 1, '🧘', 'Hatha yoga, meditation & stress relief sessions'),
  ('service', 2, 'Physiotherapy (Home Visits)', 'physiotherapy-home-visits', 'service', 'health-wellness', 1, 2, '🏃', 'Post-surgery recovery & musculoskeletal rehab'),
  ('service', 2, 'Home Nursing & Elder Care', 'home-nursing-elder-care', 'service', 'health-wellness', 1, 3, '🩺', 'Qualified nurses for bedridden & elderly care'),
  ('service', 1, 'Delivery & Moving', 'delivery-moving', NULL, NULL, NULL, 16, '🚚', 'House moving, office shifting, lorry transport, courier & goods delivery'),
  ('service', 2, 'House Moving & Shifting', 'house-moving-shifting', 'service', 'delivery-moving', 1, 0, '📦', 'Packing, loading, transit & furniture reassembly'),
  ('service', 2, 'Office Relocation', 'office-relocation', 'service', 'delivery-moving', 1, 1, '🏢', 'IT equipment, files & office furniture shifting'),
  ('service', 2, 'Lorry & Truck Hire (with Driver)', 'lorry-truck-hire-with-driver', 'service', 'delivery-moving', 1, 2, '🚛', 'Dimo Batta, Canter & heavy lorries for hire'),
  ('service', 2, 'Express Courier & Parcel Delivery', 'express-courier-parcel-delivery', 'service', 'delivery-moving', 1, 3, '🛵', 'Same day city delivery & islandwide packages'),
  ('service', 1, 'Construction Services', 'construction-services', NULL, NULL, NULL, 17, '🏗️', 'House construction, renovation, roofing, aluminium & architectural plans'),
  ('service', 2, 'House Construction (Turnkey)', 'house-construction-turnkey', 'service', 'construction-services', 1, 0, '🏠', 'Foundation to finish turnkey house building'),
  ('service', 2, 'Home Renovation & Extensions', 'home-renovation-extensions', 'service', 'construction-services', 1, 1, '🔨', 'Adding floors, modernizing kitchens & remodels'),
  ('service', 2, 'Aluminium Doors & Windows', 'aluminium-doors-windows', 'service', 'construction-services', 1, 2, '🪟', 'Aluminium partitions, sliding doors & windows'),
  ('service', 2, 'Ceiling Work (i-Panel / Gypsum)', 'ceiling-work-i-panel-gypsum', 'service', 'construction-services', 1, 3, '🏛️', 'Modern gypsum board & PVC i-panel ceilings'),
  ('service', 2, 'Steel Fabrication & Gates', 'steel-fabrication-gates', 'service', 'construction-services', 1, 4, '🔥', 'Remote roller doors, wrought iron gates & grills'),
  ('service', 1, 'Repair & Maintenance', 'repair-maintenance', NULL, NULL, NULL, 18, '🔧', 'General equipment repair, welding, power tool maintenance & sharpening'),
  ('service', 2, 'General Equipment Repair', 'general-equipment-repair', 'service', 'repair-maintenance', 1, 0, '⚙️', 'Pumps, motors, compressors & mechanical tools'),
  ('service', 2, 'Power Tool Repair', 'power-tool-repair', 'service', 'repair-maintenance', 1, 1, '🪛', 'Armatures, carbon brushes & drill servicing'),
  ('service', 1, 'Legal & Professional', 'legal-professional', NULL, NULL, NULL, 19, '⚖️', 'Lawyers, notary public, deed drafting, title search & documentation'),
  ('service', 2, 'Notary Public & Deed Drafting', 'notary-public-deed-drafting', 'service', 'legal-professional', 1, 0, '📑', 'Land deeds, gift deeds & title verification'),
  ('service', 2, 'Legal Consultation', 'legal-consultation', 'service', 'legal-professional', 1, 1, '⚖️', 'Civil, corporate, family & property disputes'),
  ('service', 2, 'Affidavits & Power of Attorney', 'affidavits-power-of-attorney', 'service', 'legal-professional', 1, 2, '🖋️', 'Notarized affidavits & legal attestations'),
  ('service', 1, 'Accounting & Finance Services', 'accounting-finance-services', NULL, NULL, NULL, 20, '📊', 'Tax filing (RAMIS/VAT), bookkeeping, auditing and payroll outsourcing'),
  ('service', 2, 'Tax Consultation & RAMIS Filing', 'tax-consultation-ramis-filing', 'service', 'accounting-finance-services', 1, 0, '📑', 'Individual & company income tax, VAT, SSCL'),
  ('service', 2, 'Bookkeeping & Management Accounts', 'bookkeeping-management-accounts', 'service', 'accounting-finance-services', 1, 1, '📒', 'Monthly QuickBooks/Xero ledger maintenance'),
  ('service', 2, 'Audit & Financial Reports', 'audit-financial-reports', 'service', 'accounting-finance-services', 1, 2, '🔍', 'Statutory audit preparation & financial statements'),
  ('service', 1, 'Real Estate Services', 'real-estate-services', NULL, NULL, NULL, 21, '🏘️', 'Property valuation, real estate brokers, property management and surveying'),
  ('service', 2, 'Property Valuation (Chartered Valuer)', 'property-valuation-chartered-valuer', 'service', 'real-estate-services', 1, 0, '📜', 'Bank loan valuations & court estimates'),
  ('service', 2, 'Land Surveying (Licensed Surveyor)', 'land-surveying-licensed-surveyor', 'service', 'real-estate-services', 1, 1, '📐', 'Boundary demarcation, contour plans & sub-divisions'),
  ('service', 2, 'Real Estate Brokerage', 'real-estate-brokerage', 'service', 'real-estate-services', 1, 2, '🤝', 'Assistance in finding tenants & buyers'),
  ('service', 2, 'Property & Rental Management', 'property-rental-management', 'service', 'real-estate-services', 1, 3, '🔑', 'Rent collection, tenant vetting & property upkeep'),
  ('service', 1, 'Travel & Tourism Services', 'travel-tourism', NULL, NULL, NULL, 22, '🌴', 'Tour packages, airport drops, visa consultation and hotel bookings'),
  ('service', 2, 'Airport Drop & Pickup', 'airport-drop-pickup', 'service', 'travel-tourism', 1, 0, '✈️', 'Fixed-price transfers to/from BIA Katunayake'),
  ('service', 2, 'Sri Lanka Tour Packages & Round Trips', 'sri-lanka-tour-packages-round-trips', 'service', 'travel-tourism', 1, 1, '🌴', 'Ella, Sigiriya, Kandy, Nuwara Eliya & beach tours'),
  ('service', 2, 'Visa & Passport Assistance', 'visa-passport-assistance', 'service', 'travel-tourism', 1, 2, '🛂', 'Tourist, student & work visa application help'),
  ('service', 1, 'Pet Services', 'pet-services', NULL, NULL, NULL, 23, '🐾', 'Dog grooming, pet sitting, boarding, veterinary visits and dog training'),
  ('service', 2, 'Pet Grooming (Doorstep)', 'pet-grooming-doorstep', 'service', 'pet-services', 1, 0, '✂️', 'Bathing, fur trimming, nail clipping & tick baths'),
  ('service', 2, 'Pet Boarding & Daycare', 'pet-boarding-daycare', 'service', 'pet-services', 1, 1, '🐕', 'Safe home kennel care while you travel'),
  ('service', 2, 'Dog Training & Obedience', 'dog-training-obedience', 'service', 'pet-services', 1, 2, '🎾', 'Puppy obedience, guard training & potty habits'),
  ('service', 1, 'Security Services', 'security-services', NULL, NULL, NULL, 24, '🛡️', 'Security guard deployment, commercial surveillance and VIP protection'),
  ('service', 2, 'Security Guard Deployment', 'security-guard-deployment', 'service', 'security-services', 1, 0, '👮', 'Trained static & roving security officers'),
  ('service', 2, 'VIP Protection & Bodyguards', 'vip-protection-bodyguards', 'service', 'security-services', 1, 1, '🕶️', 'Close personal protection & event security'),
  ('service', 1, 'Agriculture Services', 'agriculture-services', NULL, NULL, NULL, 25, '🌾', 'Land clearing, paddy harvesting, tractor services and tree cutting'),
  ('service', 2, 'Tree Cutting & Dangerous Branch Removal', 'tree-cutting-dangerous-branch-removal', 'service', 'agriculture-services', 1, 0, '🪓', 'Safe tree felling near houses & power lines'),
  ('service', 2, 'Land Clearing & Earth Levelling', 'land-clearing-earth-levelling', 'service', 'agriculture-services', 1, 1, '🚜', 'JCB earthmoving, jungle clearance & grading'),
  ('service', 2, 'Tractor Ploughing & Harvesting', 'tractor-ploughing-harvesting', 'service', 'agriculture-services', 1, 2, '🌾', 'Field preparation & combine harvesting'),
  ('service', 1, 'Printing & Advertising', 'printing-advertising', NULL, NULL, NULL, 26, '🖨️', 'Banner printing, business cards, t-shirt printing, signage and flyers'),
  ('service', 2, 'Flex Banners & Signboards', 'flex-banners-signboards', 'service', 'printing-advertising', 1, 0, '🖼️', 'Large format outdoor banners, lightboards & neon signs'),
  ('service', 2, 'Business Cards & Leaflets', 'business-cards-leaflets', 'service', 'printing-advertising', 1, 1, '💳', 'Offset & digital color card printing'),
  ('service', 2, 'Custom T-Shirt & Gift Printing', 'custom-t-shirt-gift-printing', 'service', 'printing-advertising', 1, 2, '👕', 'Screen printing, embroidery & promotional gifts'),
  ('service', 1, 'Food & Catering', 'food-catering', NULL, NULL, NULL, 27, '🍽️', 'Home cooks, daily meal tiffin delivery, event catering & barbecue service'),
  ('service', 2, 'Daily Meal & Lunch Packet Delivery', 'daily-meal-lunch-packet-delivery', 'service', 'food-catering', 1, 0, '🍱', 'Home-cooked healthy lunch & dinner subscriptions'),
  ('service', 2, 'Home Cook / Party Cooking', 'home-cook-party-cooking', 'service', 'food-catering', 1, 1, '🍳', 'On-site cooking for family gatherings & alms-givings'),
  ('service', 2, 'BBQ & Live Food Stations', 'bbq-live-food-stations', 'service', 'food-catering', 1, 2, '🍖', 'Live barbecue grill and hopper stations'),
  ('service', 1, 'Cleaning & Laundry', 'cleaning-laundry', NULL, NULL, NULL, 28, '🧺', 'Dry cleaning, laundry wash & fold, iron service and shoe restoration'),
  ('service', 2, 'Laundry (Wash & Iron)', 'laundry-wash-iron', 'service', 'cleaning-laundry', 1, 0, '🧺', 'Kilogram wash, tumble dry and crisp pressing'),
  ('service', 2, 'Dry Cleaning', 'dry-cleaning', 'service', 'cleaning-laundry', 1, 1, '👔', 'Suits, bridal sarees, blazers & delicate fabrics'),
  ('service', 2, 'Curtain & Blanket Laundry', 'curtain-blanket-laundry', 'service', 'cleaning-laundry', 1, 2, '🪟', 'Heavy curtain removal, washing & re-hanging'),
  ('service', 1, 'Other Services', 'other-services', NULL, NULL, NULL, 29, '🔧', 'Specialized and custom services not listed elsewhere'),
  ('service', 2, 'General Professional Services', 'general-professional-services', 'service', 'other-services', 1, 0, '🔧', 'Other specialist services not categorized above');

-- 3. UPSERT LEVEL 1 MAIN CATEGORIES
INSERT INTO public.categories (module, name, slug, parent_id, level, status, sort_order, icon_key, description)
SELECT 
  tc.module, 
  tc.name, 
  tc.slug, 
  NULL, 
  1, 
  'active', 
  tc.sort_order, 
  tc.icon_key, 
  tc.description
FROM temp_canonical_categories tc
WHERE tc.level = 1
ON CONFLICT (module, slug) WHERE parent_id IS NULL 
DO UPDATE SET 
  name = EXCLUDED.name,
  status = 'active',
  sort_order = EXCLUDED.sort_order,
  icon_key = EXCLUDED.icon_key,
  description = EXCLUDED.description,
  updated_at = now();

-- 4. UPSERT LEVEL 2 SUBCATEGORIES
INSERT INTO public.categories (module, name, slug, parent_id, level, status, sort_order, icon_key, description)
SELECT 
  tc.module, 
  tc.name, 
  tc.slug, 
  p.id AS parent_id, 
  2, 
  'active', 
  tc.sort_order, 
  tc.icon_key, 
  tc.description
FROM temp_canonical_categories tc
JOIN public.categories p ON p.module = tc.parent_module AND p.slug = tc.parent_slug AND p.level = 1 AND p.parent_id IS NULL
WHERE tc.level = 2
ON CONFLICT (module, slug, parent_id) WHERE parent_id IS NOT NULL 
DO UPDATE SET 
  name = EXCLUDED.name,
  status = 'active',
  sort_order = EXCLUDED.sort_order,
  icon_key = EXCLUDED.icon_key,
  description = EXCLUDED.description,
  updated_at = now();

-- 5. UPSERT LEVEL 3 THIRD-LEVEL / TYPE OPTIONS
INSERT INTO public.categories (module, name, slug, parent_id, level, status, sort_order, icon_key, description)
SELECT 
  tc.module, 
  tc.name, 
  tc.slug, 
  p.id AS parent_id, 
  3, 
  'active', 
  tc.sort_order, 
  tc.icon_key, 
  tc.description
FROM temp_canonical_categories tc
JOIN temp_canonical_categories t_parent ON tc.parent_slug = t_parent.slug AND tc.parent_level = t_parent.level AND tc.parent_module = t_parent.module
JOIN public.categories p_main ON t_parent.parent_module = p_main.module AND t_parent.parent_slug = p_main.slug AND p_main.level = 1 AND p_main.parent_id IS NULL
JOIN public.categories p ON p.module = tc.parent_module AND p.slug = tc.parent_slug AND p.parent_id = p_main.id AND p.level = 2
WHERE tc.level = 3
ON CONFLICT (module, slug, parent_id) WHERE parent_id IS NOT NULL 
DO UPDATE SET 
  name = EXCLUDED.name,
  status = 'active',
  sort_order = EXCLUDED.sort_order,
  icon_key = EXCLUDED.icon_key,
  description = EXCLUDED.description,
  updated_at = now();

-- 6. SET UNMATCHED LEGACY CATEGORIES TO INACTIVE (PRESERVE DATA, DISABLE UNMATCHED)
WITH active_canonical_ids AS (
  SELECT c.id
  FROM public.categories c
  JOIN temp_canonical_categories tc1 ON c.module = tc1.module AND c.slug = tc1.slug AND c.level = 1 AND tc1.level = 1 AND c.parent_id IS NULL
  UNION ALL
  SELECT c.id
  FROM public.categories c
  JOIN temp_canonical_categories tc2 ON c.module = tc2.module AND c.slug = tc2.slug AND c.level = 2 AND tc2.level = 2
  JOIN public.categories p ON c.parent_id = p.id AND p.slug = tc2.parent_slug AND p.level = 1
  UNION ALL
  SELECT c.id
  FROM public.categories c
  JOIN temp_canonical_categories tc3 ON c.module = tc3.module AND c.slug = tc3.slug AND c.level = 3 AND tc3.level = 3
  JOIN public.categories p ON c.parent_id = p.id AND p.slug = tc3.parent_slug AND p.level = 2
)
UPDATE public.categories
SET status = 'inactive', updated_at = now()
WHERE id NOT IN (SELECT id FROM active_canonical_ids);

COMMIT;
